// Generated by dbt_charts_dive — do not edit by hand. Re-run `dbt build` to regenerate.
// Board: __BOARD_PATHS__
//
// Every design decision here was made by dbt-charts at compile time and lives in MANIFEST
// (see builder.py). This file runs the SQL live, lays the pieces out, formats values and
// wires dbt Charts' interactions: variables (one pre-rendered SQL per value combination,
// live values inlined into typed slots), hover tooltips (the ``description`` dct puts on
// every mark, in dct's row layout), drill-down links, table pagination, tabs and details.
import { useEffect, useMemo, useRef, useState, type CSSProperties, type ReactNode } from "react";
import { useDiveState, useSQLQuery } from "@motherduck/react-sql-query";
import { AlertCircle } from "lucide-react";

export const REQUIRED_DATABASES = __REQUIRED_DATABASES_JSON__;

const MANIFEST: Manifest = __MANIFEST_JSON__;

// vega + vega-lite + vega-embed, gzipped + base64 (see builder.py)
const VEGA_B64 = "__VEGA_BUNDLE_B64__";

// ─────────────────────────────────────────────────────────────────────────────
// Types (mirror dbt_charts_dive.builder's manifest)
// ─────────────────────────────────────────────────────────────────────────────
type Row = Record<string, unknown>;
type Values = Record<string, unknown>;
type Font = { family: string; size: number | null; weight: string | null; color: string | null; style: string | null };
type Pad = { top: number; right: number; bottom: number; left: number };
type Border = { width: number; color: string; radius: number };
type Plan = {
  spec: string;
  prefix: string;
  suffix: string;
  si: Record<string, string> | null;
  pct: boolean;
  sub_unit?: { floor: number; spec: string };
  small?: Plan; // KPI below dct's SI-compaction threshold
  threshold?: number;
};
type Column = {
  spark?: SparkPlan;
  key: string;
  label: string;
  align: "left" | "center" | "right" | null;
  swatch: boolean;
  format: Plan;
  time?: string; // d3-time-format spec for temporal columns
  shared?: { divisor: number; spec: string; suffix: string; repeat: boolean };
  link?: string; // dct's per-cell link template: {{ col }} / {{ col | urlencode }}
  header_link?: string;
};
type Pagination = {
  page_rows: number;
  grow_cap: number;
  control_height: number;
  sibling: number;
  boundary: number;
  prev: string;
  next: string;
  ellipsis: string;
  aux_slot_ratio: number;
  color_active: string;
  color_inactive: string;
  color_disabled: string;
  font_size: number;
  weight_active: string;
  weight_inactive: string;
  weight_chevron: string;
  item_width: number;
};
type TableSpec = {
  spark?: SparkTheme | null;
  title: string;
  subtitle: string;
  title_font: Font;
  subtitle_font: Font;
  title_height: number;
  font: Font;
  numeric_font: string;
  background: string | null;
  header: { visible: boolean; height: number; font: Font; background: string | null; rule: number };
  row: { height: number; stripe: string | null; rule: number };
  rule_color: string;
  cell_padding: number;
  page_rows: number | null;
  pagination: Pagination | null;
  link_color: string;
  symbol_mode: "all" | "anchors";
  more_font: Font;
  empty_font: Font;
  columns: Column[];
};
type KpiColors = { value_fill: string; glyph_fill: string; label_fill: string; muted: string; card_fill?: string | null; border_color?: string | null };
type Rule = { default?: boolean; is_null?: boolean; eq?: unknown; ne?: unknown; in?: unknown[]; lt?: number; lte?: number; gt?: number; gte?: number; between?: [number, number] };
type KpiSpec = {
  value: string;
  layout: {
    width: number; height: number; content_x: number;
    value_baseline: number; value_font: number; affix_font: number; glyph_font: number; value_weight: string;
    prefix_baseline: number; glyph_baseline: number;
    label_baseline_first: number; label_font_size: number; label_font_family: string; label_weight: string; label_line_height: number; label_lines: string[];
    support_baseline: number; support_font_size: number; support_weight: string | null;
  };
  colors: KpiColors;
  chrome: string | null;
  // Conditional style channels: dct resolves these rules against a row, so the Dive keeps
  // one resolved card per outcome and the live row picks (presentation._kpi_channel_cases).
  channels?: { name: string; field: string; rules: Rule[] }[];
  cases?: Record<string, { colors: KpiColors; chrome: string | null }>;
  glyph: string;
  value_font: string;
  body_font: string;
  format: Plan;
  support?: { value: string | null; glyph: string; explainer: string; value_fill: string; glyph_fill: string; format: Plan };
};
type ChartEntry = {
  id: string;
  type: string;
  kind: "vega" | "kpi" | "table" | "svg" | "spark_bar" | "unsupported";
  query?: string | null;
  width: number;
  height: number;
  pad?: Pad;
  spec?: any;
  snapshot?: Row[];
  kpi?: KpiSpec;
  spark_bar?: SparkBarSpec;
  table?: TableSpec;
  legend?: { table: TableSpec; rows: Row[] };
  svg?: string;
  message?: string;
  link?: string; // KPI card anchor / table row-band link template
};
// A pre-evaluated Jinja condition (variable ``enabled``, layout ``visible``): constant, or a
// table over the variant dimensions of the variables it reads.
type Dim = { key: string; kind: "value" | "checkbox" | "count" | "set" };
type Cond = boolean | { dims: Dim[]; table: Record<string, boolean>; default: boolean };
type Control = {
  key: string; // Dive state key
  name: string;
  input: string;
  label: string;
  default: unknown;
  options: string[];
  can_unset: boolean;
  unset_label: string;
  placeholder: string;
  type: "string" | "number" | "date" | "bool";
  enabled: Cond;
  min?: number | null;
  max?: number | null;
  step?: number | null;
};
type Slot = { token: string; key: string; member: number; type: "string" | "number" | "date" | "bool" };
type QueryVariables = { deps: string[]; dims: Dim[]; variants?: Record<string, { sql: string; slots: Slot[] }>; note?: string };
type Details = { key: string; summary: string; expanded_summary: string; expanded: boolean };
type LayoutItem = ({ chart: string } | { board: BoardNode; details?: Details }) & { visible?: Cond };
type LayoutNode = {
  type: "rows" | "cols" | "tabs";
  gap: number;
  columns?: string;
  titles?: string[];
  slugs?: string[];
  key?: string; // tabs: the Dive state key (dct's tab variable)
  default?: number;
  position?: "top" | "left";
  items: (LayoutItem | null)[];
};
type BoardNode = { title_svg: string; text_svg: string; layout: LayoutNode; variables?: Control[]; variable_notes?: string[] };
type Manifest = {
  title: string;
  built_at: string;
  bundle: { vega: string; vega_lite: string; vega_embed: string; source: string; vl_convert: string };
  style: {
    background: string; muted: string; font: Font; border_color: string; page_padding: number; card_padding: number; gap: number;
    tabs: { height: number; font: Font; active_weight: string; inactive_weight: string; active_color: string; inactive_color: string; active_fill: string | null; inactive_fill: string | null; border: Border };
    details: { summary_height: number; arrow_x: number; arrow_size: number; label_x: number; font: Font; color: string; content_y_offset: number; expanded_fill: string | null; collapsed_fill: string | null; border: Border };
    variables: {
      font: Font; label_font: Font; value_font: Font; placeholder_color: string | null; gap: number; control_gap: number; container_height: number;
      input: { height: number; background: string; padding: Pad; radius: number; focus_color: string | null; widths: { text: number; number: number; range: number; checkbox: number; daterange: number } };
    };
    tooltip: {
      background: string; line_height: number; max_width: number; gap: number; font: Font; padding: Pad; label: Font; value: Font; border: Border; shadow: boolean;
      swatch: { size: number; radius: number }; active_marker: "fill" | "triangle"; hover_emphasis: boolean; max_rows: number; abandon: number;
    };
  };
  board: BoardNode;
  queries: Record<string, string>;
  query_variables: Record<string, QueryVariables>;
  charts: Record<string, ChartEntry>;
  fonts: { css: string; families: string[] };
};

// ─────────────────────────────────────────────────────────────────────────────
// Vega bundle + embedded fonts
// ─────────────────────────────────────────────────────────────────────────────
let vegaPromise: Promise<any> | null = null;
function loadVega(): Promise<any> {
  const w = window as any;
  if (!vegaPromise) {
    vegaPromise = (async () => {
      if (MANIFEST.fonts.css && !document.getElementById("dcd-fonts")) {
        const st = document.createElement("style");
        st.id = "dcd-fonts";
        st.textContent = MANIFEST.fonts.css;
        document.head.appendChild(st);
      }
      if (!w.vegaEmbed) {
        const raw = atob(VEGA_B64);
        const bytes = new Uint8Array(raw.length);
        for (let i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i);
        const ds = new DecompressionStream("gzip");
        const writer = ds.writable.getWriter();
        writer.write(bytes);
        writer.close();
        const code = await new Response(ds.readable).text();
        // The UMD wrappers attach to globalThis when `exports`/`module`/`define` are undefined.
        new Function("require", "exports", "module", "define", code)(undefined, undefined, undefined, undefined);
        if (!w.vegaEmbed) throw new Error("vega bundle loaded but window.vegaEmbed is missing");
      }
      // Fonts must be resolvable before Vega measures text.
      const fonts = (document as any).fonts;
      if (fonts?.load) await Promise.all(MANIFEST.fonts.families.map((f) => fonts.load(`12px "${f}"`).catch(() => null)));
      return w;
    })();
  }
  return vegaPromise;
}

function useVega() {
  const [state, setState] = useState<{ ready: boolean; error: string | null }>({ ready: false, error: null });
  useEffect(() => {
    let cancelled = false;
    loadVega()
      .then(() => !cancelled && setState({ ready: true, error: null }))
      .catch((e) => !cancelled && setState({ ready: false, error: String(e) }));
    return () => {
      cancelled = true;
    };
  }, []);
  return state;
}

// ─────────────────────────────────────────────────────────────────────────────
// Variables — values → SQL (builder's variant tables) and conditions
// ─────────────────────────────────────────────────────────────────────────────
function allControls(node: BoardNode): Control[] {
  const out: Control[] = [...(node.variables ?? [])];
  for (const it of node.layout.items) if (it && "board" in it) out.push(...allControls(it.board));
  return out;
}
const CONTROLS = allControls(MANIFEST.board);
const DEFAULTS: Values = Object.fromEntries(CONTROLS.map((c) => [c.key, c.default]));

const isUnset = (v: unknown): boolean => v == null || v === "" || (Array.isArray(v) && (v.length === 0 || v.some((x) => x == null || x === "")));

/** The variant-table coordinate of one value (mirrors ``variables.py``'s member keys). */
function dimKey(d: Dim, v: unknown): string {
  if (d.kind === "checkbox") return v ? "true" : "false";
  if (d.kind === "count") return Array.isArray(v) ? String(v.length) : isUnset(v) ? "0" : "1";
  if (d.kind === "set") return isUnset(v) ? "unset" : "set";
  return isUnset(v) ? "" : String(v);
}

function condValue(c: Cond | undefined, values: Values): boolean {
  if (c === undefined) return true;
  if (typeof c === "boolean") return c;
  const k = c.dims.map((d) => dimKey(d, values[d.key])).join("|");
  return k in c.table ? c.table[k] : c.default;
}

/** dbt-charts' ``_to_sql_literal`` for the value a slot stands for. A slot is the only
 *  place a value enters the statement, and it always enters as a literal of the slot's
 *  own type — whatever the viewer put in the control or the URL. */
function literal(v: unknown, s: Slot): string {
  if (Array.isArray(v)) v = v[s.member];
  if (v == null || v === "") return "NULL";
  if (s.type === "number") {
    const n = Number(v);
    return Number.isFinite(n) ? String(n) : "NULL";
  }
  if (s.type === "bool") return v === true || v === "true" ? "TRUE" : "FALSE";
  if (s.type === "date") {
    const d = String(v).slice(0, 10);
    return /^\d{4}-\d{2}-\d{2}$/.test(d) ? `DATE '${d}'` : "NULL";
  }
  return "'" + String(v).replace(/'/g, "''") + "'";
}

/** The SQL for ``qname`` at ``values``: the default text unless a control feeds the query. */
function sqlFor(qname: string, values: Values): string {
  const qv = MANIFEST.query_variables[qname];
  if (!qv || !qv.variants) return MANIFEST.queries[qname];
  const v = qv.variants[qv.dims.map((d) => dimKey(d, values[d.key])).join("|")];
  if (!v) return MANIFEST.queries[qname];
  let sql = v.sql;
  for (const s of v.slots) sql = sql.split(s.token).join(literal(values[s.key], s));
  return sql;
}

/** One control's state, persisted in the Dive (URL/state bag) under dct's variable name. */
function VariableBinding({ control, onBind }: { control: Control; onBind: (key: string, value: unknown, set: (v: unknown) => void) => void }) {
  const [value, setValue] = useDiveState(control.key, control.default);
  useEffect(() => {
    onBind(control.key, value, setValue);
  }, [control.key, value]);
  return null;
}

// ─────────────────────────────────────────────────────────────────────────────
// Query layer — one useSQLQuery per board query, shared by every chart
// ─────────────────────────────────────────────────────────────────────────────
type QueryState = { rows: Row[] | null; loading: boolean; error: string | null };
type Results = Record<string, QueryState>;

const _exactlyADouble = (v: bigint) => v >= -9007199254740991n && v <= 9007199254740991n;

function normalizeValue(v: unknown): unknown {
  if (v == null) return null;
  const t = typeof v;
  // A number outside the double's exact range keeps its own digits; the formatter reads
  // those, and a link or an id that goes through is the one the warehouse has.
  if (t === "bigint") return _exactlyADouble(v as bigint) ? Number(v) : String(v);
  if (t === "number" || t === "string" || t === "boolean") return v;
  if (Array.isArray(v)) return v.map(normalizeValue);  // a LIST column: a sparkline's series
  const o = v as any;
  if (typeof o.toJson === "function") return o.toJson();
  if (Array.isArray(o.values)) return o.values.map(normalizeValue);
  const s = String(o);
  const n = Number(s);
  // DECIMAL objects stringify to their numeric text.
  return s !== "" && !Number.isNaN(n) && /^-?\d/.test(s) && !/[-:T]/.test(s.slice(1)) ? n : s;
}

function QueryLoader({ name, sql, onChange }: { name: string; sql: string; onChange: (name: string, s: QueryState) => void }) {
  const q = useSQLQuery(sql);
  const rows = useMemo(
    () => (Array.isArray(q.data) ? (q.data as Row[]).map((r) => Object.fromEntries(Object.keys(r).map((k) => [k, normalizeValue(r[k])]))) : null),
    [q.data],
  );
  useEffect(() => {
    onChange(name, { rows, loading: q.isLoading, error: q.isError ? String(q.error) : null });
  }, [name, rows, q.isLoading, q.isError, q.error]);
  return null;
}

// ─────────────────────────────────────────────────────────────────────────────
// Formatting — runs dbt-charts' format plan with d3-format from the Vega bundle
// ─────────────────────────────────────────────────────────────────────────────
const d3 = () => (window as any).vega.defaultLocale();

/** (prefix, number, suffix, magnitude) — the three lanes dct's ``format_kpi_parts`` returns,
 *  plus the magnitude token (K/mn/…) the suffix lane starts with, when it does. */
const NUMERIC_TEXT = /^-?\d+(\.\d+)?$/;
/** A column a double cannot hold arrives as its own digits (sql.column_casts), so that
 *  a link or an export carries the number the warehouse has. dct formats through a float. */
const asNumber = (v: unknown): unknown => (typeof v === "string" && NUMERIC_TEXT.test(v) ? Number(v) : v);

function fmt(v: unknown, p: Plan): [string, string, string, string] {
  if (v == null) return ["", "", "", ""];
  v = asNumber(v);
  if (typeof v !== "number") return ["", String(v), "", ""];
  if (p.small && p.threshold != null && Math.abs(v) < p.threshold) p = p.small;
  let spec = p.spec;
  if (p.sub_unit && p.sub_unit.floor < Math.abs(v) && Math.abs(v) < 1) spec = p.sub_unit.spec;
  if (!spec) spec = Number.isInteger(v) ? ",d" : ",.2f"; // dct's exact-digits fallback
  let s: string = d3().format(spec)(v);
  let mag = "";
  let pct = "";
  if (p.si) for (const k of Object.keys(p.si)) if (s.endsWith(k)) { mag = p.si[k]; s = s.slice(0, -k.length); break; }
  if (p.pct && s.endsWith("%")) { pct = "%"; s = s.slice(0, -1); }
  return [p.prefix, s, mag + pct + p.suffix, mag];
}

const css = (f: Font): CSSProperties => ({
  fontFamily: f.family,
  fontSize: f.size ?? undefined,
  fontWeight: f.weight ?? undefined,
  color: f.color ?? undefined,
  fontStyle: f.style ?? undefined,
});

// ─────────────────────────────────────────────────────────────────────────────
// Links — dct's ``resolve_cell_link`` (table_support.py) over a live row
// ─────────────────────────────────────────────────────────────────────────────
/** Python's ``urllib.parse.quote_plus``: ``_.-~`` and alphanumerics kept, space → ``+``. */
function quotePlus(s: string): string {
  return encodeURIComponent(s)
    .replace(/[!'()*]/g, (c) => "%" + c.charCodeAt(0).toString(16).toUpperCase())
    .replace(/%20/g, "+");
}
const LINK_TEMPLATE = /\{\{\s*(\w+)(?:\s*\|\s*(\w+))?\s*\}\}/g;
function resolveCellLink(link: string, row: Row, columns: string[]): string | null {
  if (columns.includes(link)) return row[link] == null ? null : String(row[link]);
  if (!LINK_TEMPLATE.test(link)) return link;
  let hasNone = false;
  const out = link.replace(LINK_TEMPLATE, (_m, col: string, filter?: string) => {
    const v = row[col];
    if (v == null) { hasNone = true; return ""; }
    return filter === "urlencode" ? quotePlus(String(v)) : String(v);
  });
  return hasNone || !out ? null : out;
}
const Anchor = ({ href, children, color, className }: { href: string; children: ReactNode; color?: string; className?: string }) => (
  <a href={href} target="_blank" rel="noopener noreferrer" className={className} style={{ color, textDecoration: "none" }}>
    {children}
  </a>
);

// ─────────────────────────────────────────────────────────────────────────────
// Tooltip — dct's structured tooltip (chart_interactivity.js) over Vega's per-mark
// ``description``, which is exactly the expression dct compiled into the spec
// ─────────────────────────────────────────────────────────────────────────────
type Entry = { role: "header" | "series" | "order" | "value" | "total"; value: string; label?: string; swatch?: boolean; muted?: boolean };
const ROLE_HEADER = "⁡", ROLE_HEADER_SWATCHED = "⁤", ROLE_SERIES = "⁢", ROLE_TOTAL = "⁣", ROLE_ORDER = "‌", MUTED = "⁠";

function parseAriaLabel(label: string | null): Entry[] {
  const entries: Entry[] = [];
  if (!label) return entries;
  for (const raw of label.split(";")) {
    let pair = raw.trim();
    if (!pair) continue;
    let muted = false;
    if (pair.charAt(0) === MUTED) { muted = true; pair = pair.slice(1); }
    const marker = pair.charAt(0);
    if (marker === ROLE_HEADER || marker === ROLE_HEADER_SWATCHED) { entries.push({ role: "header", swatch: marker === ROLE_HEADER_SWATCHED, value: pair.slice(1) }); continue; }
    if (marker === ROLE_SERIES) { entries.push({ role: "series", value: pair.slice(1) }); continue; }
    if (marker === ROLE_ORDER) { entries.push({ role: "order", value: pair.slice(1) }); continue; }
    const isTotal = marker === ROLE_TOTAL;
    const rest = isTotal ? pair.slice(1) : pair;
    const i = rest.indexOf(":");
    if (i === -1) continue;
    const key = rest.slice(0, i).trim();
    if (!key) continue;
    entries.push({ role: isTotal ? "total" : "value", label: key, value: rest.slice(i + 1).trim(), muted });
  }
  return entries;
}
const isDataLabel = (label: string | null) => !!label && (label.includes(ROLE_HEADER) || label.includes(ROLE_SERIES) || label.includes(ROLE_HEADER_SWATCHED) || label.includes(ROLE_TOTAL) || label.includes(":"));
const headerKey = (e: Entry[]) => e.filter((x) => x.role === "header").map((x) => x.value).join("|");
const seriesOf = (e: Entry[]) => e.find((x) => x.role === "series");
const orderOf = (e: Entry[]) => { const o = e.find((x) => x.role === "order"); const n = o ? Number(o.value) : NaN; return Number.isFinite(n) ? n : null; };
const fieldName = (k: string) => k.replace(/[_-]/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
const markColor = (el: Element): string | null => {
  for (const attr of ["fill", "stroke"]) {
    const v = el.getAttribute(attr);
    if (v && v !== "none" && v !== "transparent") return v;
  }
  return null;
};

type TooltipState = { el: HTMLDivElement; dimmed: HTMLElement[] };
let tooltipState: TooltipState | null = null;
function tooltipBox(): TooltipState {
  if (tooltipState && document.body.contains(tooltipState.el)) return tooltipState;
  const T = MANIFEST.style.tooltip;
  const el = document.createElement("div");
  el.className = "dcd-tooltip";
  el.setAttribute("role", "tooltip");
  Object.assign(el.style, {
    position: "fixed", display: "none", pointerEvents: "none", zIndex: "10000", width: "max-content",
    background: T.background, maxWidth: `${T.max_width}px`, borderRadius: `${T.border.radius}px`,
    padding: `${T.padding.top}px ${T.padding.right}px ${T.padding.bottom}px ${T.padding.left}px`,
    fontSize: `${T.font.size ?? 13}px`, fontFamily: T.font.family, lineHeight: String(T.line_height),
    border: `${T.border.width}px solid ${T.border.color}`, boxShadow: T.shadow ? "0 10px 25px rgba(15, 23, 42, 0.25)" : "none",
  } as CSSProperties);
  document.body.appendChild(el);
  tooltipState = { el, dimmed: [] };
  return tooltipState;
}
function hideTooltip() {
  if (!tooltipState) return;
  tooltipState.el.style.display = "none";
  for (const d of tooltipState.dimmed) d.style.removeProperty("opacity");
  tooltipState.dimmed = [];
}
const esc = (s: string) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/"/g, "&quot;");
function tooltipHtml(hovered: Entry[], matches: { entries: Entry[]; color: string | null; active: boolean }[]): string {
  const T = MANIFEST.style.tooltip;
  const swatch = (c: string | null) => (c ? `<span style="display:inline-block;width:${T.swatch.size}px;height:${T.swatch.size}px;border-radius:${T.swatch.radius}px;background:${c};margin-right:6px;flex-shrink:0"></span>` : "");
  const header = (e: Entry, c: string | null) => `<div class="dcd-tt-header" style="display:flex;align-items:center;font-weight:700;padding:2px 0 4px;color:${T.value.color}">${e.swatch ? swatch(c) : ""}${esc(e.value)}</div>`;
  const valueRow = (e: Entry, total: boolean) =>
    `<div class="dcd-tt-${total ? "total" : "value"}" style="display:flex;justify-content:space-between;gap:${T.gap}px;${total ? `margin-top:4px;padding-top:4px;border-top:1px solid ${T.border.color}` : "padding:2px 0"}">` +
    `<span style="color:${T.label.color};font-weight:${total ? T.value.weight : T.label.weight}">${esc(fieldName(e.label ?? ""))}</span>` +
    `<span style="color:${e.muted ? T.label.color : T.value.color};font-weight:${T.value.weight};text-align:right;font-variant-numeric:tabular-nums lining-nums">${esc(e.value)}</span></div>`;
  if (matches.length <= 1) {
    const c = matches[0]?.color ?? null;
    return hovered
      .map((e) => (e.role === "header" ? header(e, c) : e.role === "series" ? `<div class="dcd-tt-series" style="display:flex;align-items:center;padding:2px 0;color:${T.value.color}">${swatch(c)}${esc(e.value)}</div>` : e.role === "order" ? "" : valueRow(e, e.role === "total")))
      .join("");
  }
  // x-unified: every series at the hovered x, one grid row each, "+N more" past max_rows
  const hasPct = matches.some((m) => m.entries.filter((e) => e.role === "value").length > 1);
  const cap = T.max_rows;
  let shown = matches;
  let remainder = 0;
  if (matches.length > cap) {
    shown = matches.slice(0, cap - 1);
    const active = matches.find((m) => m.active);
    if (active && !shown.includes(active)) shown = [...shown.slice(0, cap - 2), active];
    remainder = matches.length - shown.length;
  }
  const total = matches.map((m) => m.entries.find((e) => e.role === "total")).find(Boolean);
  const cell = (html: string, style: string) => `<div style="padding:2px 8px 2px 0;${style}">${html}</div>`;
  const row = (m: { entries: Entry[]; color: string | null; active: boolean }) => {
    const s = seriesOf(m.entries);
    const values = m.entries.filter((e) => e.role === "value");
    const bg = m.active && T.active_marker === "fill" ? "background:rgba(127,127,127,0.16);" : "";
    const num = "text-align:right;font-variant-numeric:tabular-nums lining-nums;font-weight:" + T.value.weight + ";";
    return (
      `<div class="dcd-tt-row" data-active="${m.active}" style="display:contents">` +
      cell(swatch(m.color), bg + "display:flex;align-items:center;") +
      cell(esc(s ? s.value : fieldName(values[0]?.label ?? "")), bg + `color:${T.label.color};`) +
      (hasPct ? cell(esc(values[0]?.value ?? ""), bg + num + `color:${T.value.color};`) : "") +
      cell(esc(hasPct ? values[values.length - 1]?.value ?? "" : values[0]?.value ?? ""), bg + num + `color:${hasPct ? T.label.color : T.value.color};`) +
      "</div>"
    );
  };
  const cols = hasPct ? "auto minmax(0,1fr) auto auto" : "auto minmax(0,1fr) auto";
  let html = `<div style="display:grid;grid-template-columns:${cols};column-gap:0;align-items:center">`;
  html += `<div style="grid-column:1/-1;border-bottom:1px solid ${T.border.color};padding-bottom:4px;margin-bottom:4px">${hovered.filter((e) => e.role === "header").map((e) => header(e, null)).join("")}</div>`;
  html += shown.map(row).join("");
  if (remainder) html += `<div class="dcd-tt-more" style="grid-column:1/-1;font-style:italic;color:${T.label.color};padding:2px 8px">+${remainder} more</div>`;
  if (total) html += `<div style="grid-column:1/-1">${valueRow(total, true)}</div>`;
  return html + "</div>";
}

/** vega-embed tooltip handler for one chart: dct's bubble for the hovered mark, plus its
 *  hover emphasis (every mark the bubble is not describing recedes). */
function makeTooltipHandler(container: HTMLElement) {
  return (_handler: unknown, event: MouseEvent, item: any, value: unknown) => {
    if (value == null || !item) return hideTooltip();
    const T = MANIFEST.style.tooltip;
    const marks = Array.from(container.querySelectorAll(".role-mark [aria-label]")).filter((m) => isDataLabel(m.getAttribute("aria-label")));
    let description: string | null = item.description == null ? null : String(item.description);
    if (description == null) {
      // dct's own hover targets (an invisible point over each line datum, an area's fill) carry
      // no description; chart_interactivity.js snaps to the nearest labelled data mark.
      let best: Element | null = null;
      let bestD = 24 * 24;
      for (const m of marks) {
        const r = m.getBoundingClientRect();
        const dx = Math.max(r.left - event.clientX, 0, event.clientX - r.right);
        const dy = Math.max(r.top - event.clientY, 0, event.clientY - r.bottom);
        if (dx * dx + dy * dy < bestD) { bestD = dx * dx + dy * dy; best = m; }
      }
      description = best ? best.getAttribute("aria-label") : null;
    }
    if (description == null) return hideTooltip();
    const hovered = parseAriaLabel(description);
    if (!hovered.length) return hideTooltip();
    const hk = headerKey(hovered);
    type M = { entries: Entry[]; color: string | null; active: boolean; el: Element; order: number | null; i: number };
    let matches: M[] = [];
    if (hk) {
      const seen = new Set<string>();
      marks.forEach((m, i) => {
        const entries = parseAriaLabel(m.getAttribute("aria-label"));
        if (headerKey(entries) !== hk) return;
        const key = hk + "|" + (seriesOf(entries)?.value ?? "");
        if (seen.has(key)) return;
        seen.add(key);
        matches.push({ entries, color: markColor(m), active: m.getAttribute("aria-label") === description, el: m, order: orderOf(entries), i });
      });
      if (matches.some((m) => m.order != null)) matches.sort((a, b) => (a.order ?? 1e9) - (b.order ?? 1e9) || a.i - b.i);
    }
    if (matches.length < 2 || matches.length > T.abandon) {
      const own = marks.find((m) => m.getAttribute("aria-label") === description);
      matches = [{ entries: hovered, color: own ? markColor(own) : null, active: true, el: own ?? container, order: null, i: 0 }];
    }
    const st = tooltipBox();
    st.el.innerHTML = tooltipHtml(hovered, matches);
    st.el.style.display = "block";
    const r = st.el.getBoundingClientRect();
    st.el.style.left = `${Math.max(4, Math.min(event.clientX + 12, window.innerWidth - r.width - 4))}px`;
    st.el.style.top = `${Math.max(4, Math.min(event.clientY + 12, window.innerHeight - r.height - 4))}px`;
    for (const d of st.dimmed) d.style.removeProperty("opacity");
    st.dimmed = [];
    if (T.hover_emphasis) {
      const kept = new Set(matches.map((m) => m.el.getAttribute("aria-label")));
      for (const m of marks) {
        if (kept.has(m.getAttribute("aria-label")) || m.tagName === "text") continue;
        (m as HTMLElement).style.opacity = "0.3";
        st.dimmed.push(m as HTMLElement);
      }
    }
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Pieces
// ─────────────────────────────────────────────────────────────────────────────
function Svg({ html }: { html: string }) {
  return html ? <div className="dcd-svg" dangerouslySetInnerHTML={{ __html: html }} /> : null;
}

function ErrorBox({ message }: { message: string }) {
  return (
    <div className="flex items-start gap-2 rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700" role="alert">
      <AlertCircle size={16} className="mt-0.5 shrink-0" />
      <span className="break-words">{message}</span>
    </div>
  );
}

function VegaChart({ entry, rows }: { entry: ChartEntry; rows: Row[] }) {
  const ref = useRef<HTMLDivElement>(null);
  const [renderError, setRenderError] = useState<string | null>(null);
  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    let view: any = null;
    let cancelled = false;
    // dct compiled against a snapshot; the rows are live. They go in as the dataset the
    // compiler named (specs.LIVE_ROWS), which is what a choropleth's lookup reads too.
    const spec = { ...entry.spec, datasets: { ...(entry.spec.datasets ?? {}), dcd_rows: rows } };
    (window as any)
      .vegaEmbed(el, spec, {
        actions: false,
        renderer: "svg",
        mode: "vega-lite",
        tooltip: makeTooltipHandler(el),
        // ``link:`` → dct's encoding.href: a click on the mark opens it (Vega's handleHref);
        // the loader supplies the anchor's target/rel.
        loader: { target: "_blank", rel: "noopener noreferrer" },
      })
      .then((res: any) => {
        if (cancelled) return res.view.finalize();
        view = res.view;
        (el as any).__dcdView = view; // the live view, for inspection (the e2e runners read the scenegraph)
        const svg = el.querySelector("svg");
        if (svg) {
          const w = parseFloat(svg.getAttribute("width") || "0");
          const h = parseFloat(svg.getAttribute("height") || "0");
          if (w && h && !svg.getAttribute("viewBox")) svg.setAttribute("viewBox", `0 0 ${w} ${h}`);
          svg.style.maxWidth = "100%";
          svg.style.height = "auto";
        }
        setRenderError(null);
      })
      .catch((e: unknown) => !cancelled && setRenderError(String(e)));
    return () => {
      cancelled = true;
      hideTooltip();
      if (view) view.finalize();
    };
  }, [entry, rows]);
  return (
    <div onMouseLeave={hideTooltip}>
      {renderError && <ErrorBox message={renderError} />}
      <div ref={ref} />
    </div>
  );
}

/** dct's stacked KPI (``_emit_kpi_stacked``): every coordinate comes from its layout pass. */
/** dct's ``match_predicate`` for one rule (``_conditional_formatting.py``). */
function ruleMatches(r: Rule, v: unknown): boolean {
  if (r.default) return true;
  if (r.is_null != null) return (v == null) === r.is_null;
  if (r.eq != null) return (typeof v === "boolean") === (typeof r.eq === "boolean") && v === r.eq;
  if (r.ne != null) return (typeof v === "boolean") !== (typeof r.ne === "boolean") || v !== r.ne;
  if (r.in != null) return r.in.some((candidate) => String(candidate) === String(v));
  const n = typeof v === "number" ? v : Number(v);
  if (!Number.isFinite(n)) return false;
  if (r.lt != null) return n < r.lt;
  if (r.lte != null) return n <= r.lte;
  if (r.gt != null) return n > r.gt;
  if (r.gte != null) return n >= r.gte;
  if (r.between != null) return r.between[0] <= n && n <= r.between[1];
  return false;
}

/** Which precompiled card this row selects: per channel, the last rule that matches. */
function kpiCase(k: KpiSpec, row: Row): { colors: KpiColors; chrome: string | null } {
  if (!k.channels || !k.cases) return k;
  const key = k.channels.map((ch) => ch.rules.reduce((hit, rule, i) => (ruleMatches(rule, row[ch.field]) ? String(i) : hit), "base")).join("|");
  return k.cases[key] ?? k;
}

function Kpi({ k, rows, link }: { k: KpiSpec; rows: Row[]; link?: string }) {
  const row = rows[0] ?? {};
  const raw = asNumber(row[k.value]);
  const numeric = typeof raw === "number";
  const [pre, num, suf] = fmt(raw, k.format);
  const L = k.layout;
  const resolved = kpiCase(k, row);
  const C = resolved.colors;
  const S = k.support;
  const supportText = S && S.value ? fmt(asNumber(row[S.value]), S.format).join("") : "";
  const svg = (
    <svg width={L.width} height={L.height} viewBox={`0 0 ${L.width} ${L.height}`} style={{ display: "block", maxWidth: "100%" }}>
      {resolved.chrome && <g dangerouslySetInnerHTML={{ __html: resolved.chrome }} />}
      <text x={L.content_x} y={L.value_baseline} fontFamily={k.value_font} fontWeight={L.value_weight}>
        {k.glyph && <tspan y={L.glyph_baseline} fontSize={L.glyph_font} fill={C.glyph_fill}>{k.glyph + " "}</tspan>}
        {numeric && pre && <tspan y={L.prefix_baseline} fontSize={L.affix_font} fill={C.value_fill}>{pre}</tspan>}
        <tspan y={L.value_baseline} fontSize={L.value_font} fill={C.value_fill}>{num}</tspan>
        {numeric && suf && <tspan y={L.value_baseline} fontSize={L.affix_font} fill={C.value_fill} dx="2">{suf}</tspan>}
      </text>
      {L.label_lines.length > 0 && (
        <text fontFamily={L.label_font_family} fontSize={L.label_font_size} fill={C.label_fill} fontWeight={L.label_weight}>
          {L.label_lines.map((line, i) => (
            <tspan key={i} x={L.content_x} y={L.label_baseline_first + i * L.label_line_height}>{line}</tspan>
          ))}
        </text>
      )}
      {S && (
        <text x={L.content_x} y={L.support_baseline} fontFamily={k.body_font} fontSize={L.support_font_size} fontWeight={L.support_weight ?? undefined}>
          {S.glyph && <tspan fill={S.glyph_fill}>{S.glyph + " "}</tspan>}
          {supportText && <tspan fill={S.value_fill}>{supportText}</tspan>}
          {S.explainer && <tspan fill={C.muted}>{(supportText || S.glyph ? " " : "") + S.explainer}</tspan>}
        </text>
      )}
    </svg>
  );
  // dct (kpi.py ``_resolve_kpi_link``): the whole card is the anchor
  const href = link ? resolveCellLink(link, row, Object.keys(row)) : null;
  return href ? <Anchor href={href} className="dcd-kpi-link">{svg}</Anchor> : svg;
}

/** dct's paginator window (``_paginator_window``): boundary pages, siblings, one ellipsis per gap. */
// ─────────────────────────────────────────────────────────────────────────────
// Spark bar — dct's own SVG renderer (render/chart/spark_bar.py), over live rows
// ─────────────────────────────────────────────────────────────────────────────
type SparkBarSpec = {
  x: string | null;
  y: string | null;
  title: string;
  subtitle: string;
  width: number;
  height: number | null;
  max_bars: number;
  float_values: boolean;
  label: { visible: boolean; width: number };
  count: { visible: boolean; width: number };
  bar: { height: number; padding: number; color: string; background: string; radius: number };
  font: Font;
  title_font: { family: string; size: number; weight: number };
  subtitle_size: number;
  muted: string;
  layout: {
    side_padding: number; text_baseline_offset: number; title_height: number; title_baseline_y: number;
    more_rows_font_size: number; more_rows_offset_y: number; more_rows_bottom_padding: number; avg_char_width_px: number;
  };
};

/** dct's ``_signed_fraction``: a value's magnitude as a fraction of the largest one. */
function signedFraction(value: number, maxValue: number, signed: boolean): { fraction: number; negative: boolean } {
  if (!Number.isFinite(value)) return { fraction: 0, negative: false };
  if (!signed) {
    const clamped = Math.max(0, Math.min(value, maxValue));
    return { fraction: maxValue > 0 ? clamped / maxValue : 0, negative: false };
  }
  const clamped = Math.max(-maxValue, Math.min(value, maxValue));
  return { fraction: maxValue > 0 ? Math.abs(clamped) / maxValue : 0, negative: clamped < 0 };
}

/** Python's ``f"{x:.1f}"``.
 *
 *  ``toFixed`` already rounds the exact binary value correctly; where it differs from Python
 *  is a tie, which it breaks away from zero and Python breaks to even. A value that is
 *  exactly halfway at one decimal is an odd quarter (0.25, -1.75, …) and nothing else — a
 *  fifth cannot be a double — so that is the one case to correct, and multiplying by ten
 *  first (which invents ties that the value does not have, 0.15 being the classic) is what
 *  has to be avoided. */
function fixed1(value: number): string {
  const quarters = value * 4;  // exact whenever the value is one
  if (Number.isInteger(quarters) && Math.abs(quarters) % 2 === 1) {
    const tenths = Math.trunc(value * 10);
    return ((tenths % 2 === 0 ? tenths : tenths + Math.sign(value)) / 10).toFixed(1);
  }
  return value.toFixed(1);
}

const group = (n: number, digits: number) => n.toLocaleString("en-US", { minimumFractionDigits: digits, maximumFractionDigits: digits });

/** dct's count lane (`spark_bar._render_spark_bar_row`): an int column groups its digits, a
 *  float column prints a whole number bare and anything else to one decimal. */
function sparkCount(value: number, floatColumn: boolean): string {
  if (!floatColumn) return group(value, 0);
  return Number.isInteger(value) ? String(Math.trunc(value)) : group(Number(fixed1(value)), 1);
}

/** The one decimal dct writes a coordinate to — and Python's rounding of the tie. */
const px = (n: number) => Number(fixed1(n));  // a coordinate, as dct writes it: one decimal

function SparkBar({ s, rows }: { s: SparkBarSpec; rows: Row[] }) {
  const visible = rows.slice(0, s.max_bars);
  const L = s.layout;
  const rowHeight = s.bar.height + s.bar.padding;
  const titleHeight = s.title ? L.title_height + (s.subtitle ? s.title_font.size : 0) : 0;
  const height = s.height ?? titleHeight + visible.length * rowHeight + s.bar.padding;
  const leftPadding = s.label.visible ? s.label.width : L.side_padding;
  const rightPadding = s.count.visible ? s.count.width : L.side_padding;
  const barAreaWidth = Math.max(s.width - leftPadding - rightPadding, 20);
  const values = visible.map((r) => (s.x ? Number(asNumber(r[s.x]) ?? 0) : 0)).map((v) => (Number.isFinite(v) ? v : 0));
  const signed = values.some((v) => v < 0);
  const maxValue = Math.max(...values.map(Math.abs), 0) || 1;
  const maxLabelChars = Math.trunc(s.label.width / L.avg_char_width_px);
  const more = rows.length - visible.length;
  const moreY = px(titleHeight + visible.length * rowHeight + L.more_rows_offset_y);
  const svgHeight = more > 0 ? moreY + L.more_rows_bottom_padding : height;
  const text = { fontFamily: s.font.family, fontSize: s.font.size ?? undefined, fill: s.font.color ?? undefined };

  return (
    <svg xmlns="http://www.w3.org/2000/svg" data-dcd-spark="" width={s.width} height={svgHeight} viewBox={`0 0 ${s.width} ${svgHeight}`} style={{ display: "block", maxWidth: "100%" }}>
      {s.title && (
        <text x={0} y={L.title_baseline_y} fontSize={s.title_font.size} fontWeight={s.title_font.weight} fill={s.font.color ?? undefined} fontFamily={s.title_font.family} data-authored-kind="title">
          {s.title}
        </text>
      )}
      {s.title && s.subtitle && (
        <text x={0} y={L.title_baseline_y + s.title_font.size} fontSize={s.subtitle_size} fill={s.muted} fontFamily={s.font.family} data-authored-kind="subtitle">
          {s.subtitle}
        </text>
      )}
      {visible.map((row, i) => {
        const rowY = px(titleHeight + i * rowHeight);
        const { fraction, negative } = signedFraction(values[i], maxValue, signed);
        const half = barAreaWidth / 2;
        const barWidth = px(signed ? fraction * half : fraction * barAreaWidth);
        const fillX = px(signed ? leftPadding + (negative ? half - barWidth : half) : leftPadding);
        const raw = s.y ? String(row[s.y] ?? "") : `Item ${i + 1}`;
        const label = raw.length > maxLabelChars ? raw.slice(0, maxLabelChars - 2) + "..." : raw;
        const baseline = px(rowY + s.bar.height / 2 + L.text_baseline_offset);
        return (
          <g key={i}>
            {s.label.visible && <text x={0} y={baseline} {...text}>{label}</text>}
            <rect x={leftPadding} y={rowY} width={barAreaWidth} height={s.bar.height} fill={s.bar.background} rx={s.bar.radius} />
            {barWidth > 0 && <rect x={fillX} y={rowY} width={barWidth} height={s.bar.height} fill={s.bar.color} rx={s.bar.radius} />}
            {s.count.visible && (
              <text x={px(s.width - L.side_padding)} y={baseline} textAnchor="end" style={{ fontVariantNumeric: "tabular-nums lining-nums" }} {...text}>
                {sparkCount(values[i], s.float_values)}
              </text>
            )}
          </g>
        );
      })}
      {more > 0 && (
        <text x={s.width / 2} y={moreY} fontSize={L.more_rows_font_size} fill={s.muted} textAnchor="middle" fontStyle="italic" fontFamily={s.font.family} style={{ fontVariantNumeric: "tabular-nums lining-nums" }}>
          {`+ ${more} more`}
        </text>
      )}
    </svg>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// In-cell sparklines — dct's own renderers (render/chart/spark.py), over live rows
// ─────────────────────────────────────────────────────────────────────────────
type SparkTheme = {
  color: string;
  padding_top: number; padding_right: number; padding_bottom: number; padding_left: number;
  empty_inset_x: number; empty_stroke_color: string; empty_stroke_width: number; empty_stroke_dasharray: string;
  single_value_inset_x: number; single_value_marker_radius: number;
  columns_gap: number; columns_padding: number; columns_min_bar_height: number; columns_border_radius: number;
  column_width: number; column_height: number;
  bar_background: string; bar_color: string; bar_default_max: number; bar_border_radius: number;
  bar_label_inset_x: number; bar_label_fill: string; bar_label_fill_opacity: number;
  area_fill_opacity: number;
  negative: string; font_family: string; font_size: number;
};
type SparkPlan = {
  type: "line" | "area" | "bar" | "bar-normalize" | "column" | "columns";
  width: number | null;
  height: number;
  color: string | null;
  max: number | null;
  thresholds: [number, string][] | null;
  background: string | null;
  border_radius: number | null;
  last_visible: boolean;
  min_max_visible: boolean;
  value_visible: boolean;
  value_suffix: string | null;
  fill_opacity: number | null;
  negative_color: boolean;
};

const SPARK_WIDTH = 80;      // dct's _SPARK_WIDTH
const SPARK_BAR_WIDTH = 100; // dct's _SPARK_BAR_WIDTH
const STROKE_WIDTH = 1.5;

/** dct's ``_normalize_points``: one point per value, the series scaled into the box. */
function normalizePoints(values: number[], width: number, height: number, t: SparkTheme) {
  // A spread would blow the argument limit on a long series, and a NaN member would poison
  // both extrema where Python's min()/max() simply step over it (every comparison is false).
  const { min, max } = extrema(values);
  const range = max - min;
  const plotWidth = width - (t.padding_left + t.padding_right);
  const plotHeight = height - (t.padding_top + t.padding_bottom);
  const points = values.map((v, i) => {
    const x = t.padding_left + (i / (values.length - 1)) * plotWidth;
    const y = range > 0 ? t.padding_top + (1 - (v - min) / range) * plotHeight : t.padding_top + plotHeight / 2;
    return [px(x), px(y)] as [number, number];
  });
  return { points, min, max, minIdx: Math.max(0, values.indexOf(min)), maxIdx: Math.max(0, values.indexOf(max)), plotWidth, plotHeight };
}

/** The smallest and largest finite value, in one pass. Zeroes for a series with none. */
function extrema(values: number[]) {
  let min = Infinity;
  let max = -Infinity;
  for (const v of values) {
    if (!Number.isFinite(v)) continue;
    if (v < min) min = v;
    if (v > max) max = v;
  }
  return min > max ? { min: 0, max: 0 } : { min, max };
}

/** dct's ``_get_threshold_color``: the last bucket the value clears, buckets in order. */
function thresholdColor(value: number, thresholds: [number, string][], t: SparkTheme): string {
  let color = t.bar_color;
  for (const [at, hue] of thresholds) if (value >= at) color = hue;
  return color;
}

const FLOAT_TEXT = /^[+-]?(\d+\.?\d*|\.\d+)([eE][+-]?\d+)?$/;

/** dct's ``utils.coerce_numeric_cell``: whether a cell is a number at all, and which.
 *  A boolean is not one, a string is one only if it parses whole, and a non-finite value is
 *  a null — no mark, and no contribution to the column's scale. */
function numericCell(value: unknown): number | null {
  if (typeof value === "boolean" || value == null) return null;
  const n = typeof value === "number" ? value : typeof value === "string" && FLOAT_TEXT.test(value.trim()) ? Number(value) : NaN;
  return Number.isFinite(n) ? n : null;
}

/** A series cell's numbers. A member dct could not read at all arrives as NaN, which the
 *  renderers below skip — dct itself raises on one (``math.isfinite(None)``), and taking a
 *  whole board's render down over one null element is not worth reproducing. */
const sparkNumbers = (value: unknown): number[] =>
  (Array.isArray(value) ? value : value == null ? [] : [value]).map((v) => numericCell(v) ?? Number.NaN);

const trimZeros = (s: string) => (s.includes(".") ? s.replace(/0+$/, "").replace(/\.$/, "") : s);

/** Python's ``%g`` at its default precision, for the whole numbers dct sends it.
 *
 *  ``render_spark_bar`` prints a label through ``%g`` only when the value is integral, which
 *  is what makes an exact answer cheap: ``BigInt`` gives the integer's decimal digits with no
 *  rounding of its own, and six significant digits are taken off them half-to-even. The
 *  built-ins cannot do this — ``toExponential(5)`` breaks a tie away from zero, and would
 *  print 1234565 as 1.23457e+06 where Python prints 1.23456e+06.
 */
function gWholeNumber(value: number): string {
  if (value === 0) return Object.is(value, -0) ? "-0" : "0";
  const sign = value < 0 ? "-" : "";
  const digits = BigInt(Math.abs(value)).toString();
  if (digits.length <= 6) return sign + digits;  // fewer digits than the precision: nothing to round

  let exp = digits.length - 1;
  let kept = digits.slice(0, 6);
  const rest = digits.slice(6);
  const tie = rest[0] === "5" && !/[1-9]/.test(rest.slice(1));
  const odd = (kept.charCodeAt(5) - 48) % 2 === 1;
  if (rest[0] > "5" || (rest[0] === "5" && (!tie || odd))) {
    kept = (BigInt(kept) + 1n).toString();
    if (kept.length > 6) {
      kept = kept.slice(0, 6);
      exp += 1;
    }
  }
  if (exp < 6) return sign + kept.slice(0, exp + 1);  // unreachable while precision is 6, kept honest
  return `${sign}${trimZeros(`${kept[0]}.${kept.slice(1)}`)}e+${String(exp).padStart(2, "0")}`;
}

/** The cell's mark, or null when it would draw nothing — dct falls back to the cell text
 *  in exactly that case (`table._render_data_rows`: `if spark_content:`), so this is called
 *  as a plain function rather than mounted, and the caller decides what fills the cell. */
function sparkMark({ plan, theme, value, column, width }: { plan: SparkPlan; theme: SparkTheme; value: unknown; column: { max: number | null; negative: boolean }; width: number }) {
  const h = plan.height;
  const color = plan.color ?? theme.color;
  const radius = plan.border_radius ?? theme.bar_border_radius;
  const series = ["line", "area", "columns"].includes(plan.type);
  const values = sparkNumbers(value);
  const box = { display: "block" as const };

  if (series && values.length === 0)
    return (
      <svg xmlns="http://www.w3.org/2000/svg" width={width} height={h} viewBox={`0 0 ${width} ${h}`} style={box}>
        <line x1={theme.empty_inset_x} y1={h / 2} x2={width - theme.empty_inset_x} y2={h / 2} stroke={theme.empty_stroke_color} strokeWidth={theme.empty_stroke_width} strokeDasharray={theme.empty_stroke_dasharray} />
      </svg>
    );

  if ((plan.type === "line" || plan.type === "area") && values.length === 1)
    return (
      <svg xmlns="http://www.w3.org/2000/svg" width={width} height={h} viewBox={`0 0 ${width} ${h}`} style={box}>
        <line x1={theme.single_value_inset_x} y1={h / 2} x2={width - theme.single_value_inset_x} y2={h / 2} stroke={color} strokeWidth={STROKE_WIDTH} />
        <circle cx={width / 2} cy={h / 2} r={theme.single_value_marker_radius} fill={color} />
      </svg>
    );

  if (plan.type === "line" || plan.type === "area") {
    const norm = normalizePoints(values, width, h, theme);
    const points = norm.points.map(([x, y]) => `${x},${y}`).join(" ");
    const [lastX, lastY] = norm.points[norm.points.length - 1];
    const bottom = h - theme.padding_bottom;
    const lastX2 = theme.padding_left + norm.plotWidth;
    return (
      <svg xmlns="http://www.w3.org/2000/svg" width={width} height={h} viewBox={`0 0 ${width} ${h}`} style={box}>
        {plan.type === "area" && <polygon points={`${theme.padding_left},${bottom} ${points} ${lastX2},${bottom}`} fill={color} fillOpacity={plan.fill_opacity ?? theme.area_fill_opacity} />}
        <polyline points={points} fill="none" stroke={color} strokeWidth={STROKE_WIDTH} strokeLinecap="round" strokeLinejoin="round" />
        {plan.last_visible && <circle cx={lastX} cy={lastY} r={2.5} fill={color} />}
        {plan.type === "line" && plan.min_max_visible && [norm.minIdx, norm.maxIdx].map((idx, i) => <circle key={i} cx={norm.points[idx][0]} cy={norm.points[idx][1]} r={2} fill={color} />)}
      </svg>
    );
  }

  if (plan.type === "columns" && !values.some((v) => Number.isFinite(v))) return null;

  if (plan.type === "columns") {
    const gap = theme.columns_gap;
    const pad = theme.columns_padding;
    const plotHeight = h - 2 * pad;
    const barWidth = (width - gap * (values.length - 1)) / values.length;
    const { min, max } = extrema(values);
    const negative = min < 0;
    const maxAbs = Math.max(Math.abs(min), Math.abs(max), 0);
    const range = max - min;
    return (
      <svg xmlns="http://www.w3.org/2000/svg" width={width} height={h} viewBox={`0 0 ${width} ${h}`} style={box}>
        {values.map((v, i) => {
          if (!Number.isFinite(v)) return null;
          const x = i * (barWidth + gap);
          if (negative) {
            const half = plotHeight / 2;
            const midY = pad + half;
            const s = signedFraction(v, maxAbs, true);
            const barHeight = Math.max(theme.columns_min_bar_height, s.fraction * half);
            const fill = s.negative && plan.negative_color ? theme.negative : color;
            return <rect key={i} x={px(x)} y={px(s.negative ? midY : midY - barHeight)} width={px(barWidth)} height={px(barHeight)} fill={fill} rx={theme.columns_border_radius} />;
          }
          const barHeight = range > 0 ? Math.max(theme.columns_min_bar_height, ((v - min) / range) * plotHeight) : plotHeight / 2;
          return <rect key={i} x={px(x)} y={px(h - pad - barHeight)} width={px(barWidth)} height={px(barHeight)} fill={color} rx={theme.columns_border_radius} />;
        })}
      </svg>
    );
  }

  // bar / bar-normalize / column: one value, scaled against a ceiling the column shares.
  // dct puts the raw cell through `coerce_numeric_cell` before it draws anything here
  // (`table._render_spark_cell`), so a boolean, an empty string and a list are each "not a
  // number in this column" and leave the cell to its text rather than to a zero-width bar.
  const v = numericCell(value);
  if (v === null) return null;
  const maxValue = plan.max ?? column.max ?? theme.bar_default_max;
  const negative = plan.type === "bar-normalize" ? false : column.negative;
  const s = signedFraction(v, maxValue, negative);
  const clamped = Math.max(0, Math.min(v, maxValue));
  const fill = s.negative && plan.negative_color ? theme.negative : plan.color ? plan.color : plan.thresholds ? thresholdColor(clamped, plan.thresholds, theme) : theme.bar_color;

  if (plan.type === "column") {
    const w = width;  // sparkWidth() has already applied dct's theme default and its cell cap
    const fillHeight = negative ? s.fraction * (h / 2) : s.fraction * h;
    const fillY = negative ? (s.negative ? h / 2 : h / 2 - fillHeight) : h - fillHeight;
    if (fillHeight <= 0) return null;
    return (
      <svg xmlns="http://www.w3.org/2000/svg" width={w} height={h} viewBox={`0 0 ${w} ${h}`} style={box}>
        <rect x={0} y={px(fillY)} width={w} height={px(fillHeight)} fill={fill} rx={radius} />
      </svg>
    );
  }

  const fillWidth = negative ? s.fraction * (width / 2) : s.fraction * width;
  const fillX = negative ? (s.negative ? width / 2 - fillWidth : width / 2) : 0;
  if (plan.type === "bar" && fillWidth <= 0 && !plan.value_visible) return null;
  const label = (Number.isInteger(v) ? gWholeNumber(v) : fixed1(v)) + (plan.value_suffix ?? "");
  return (
    <svg xmlns="http://www.w3.org/2000/svg" width={width} height={h} viewBox={`0 0 ${width} ${h}`} style={box}>
      {plan.type === "bar-normalize" && <rect x={0} y={0} width={width} height={h} fill={plan.background ?? theme.bar_background} rx={radius} />}
      {fillWidth > 0 && <rect x={px(fillX)} y={0} width={px(fillWidth)} height={h} fill={fill} rx={radius} />}
      {plan.value_visible && (
        <text x={width - theme.bar_label_inset_x} y={h / 2} fontSize={theme.font_size} fill={theme.bar_label_fill} fillOpacity={theme.bar_label_fill_opacity} textAnchor="end" dominantBaseline="central" fontFamily={theme.font_family} style={{ fontVariantNumeric: "tabular-nums lining-nums" }}>
          {label}
        </text>
      )}
    </svg>
  );
}

function pagerWindow(page: number, total: number, sibling: number, boundary: number, ellipsis: string): (number | string)[] {
  if (total <= 1) return total === 1 ? [1] : [];
  const must = new Set<number>();
  for (let p = 1; p <= Math.min(boundary, total); p++) must.add(p);
  for (let p = Math.max(total - boundary + 1, 1); p <= total; p++) must.add(p);
  for (let p = Math.max(page - sibling, 1); p <= Math.min(page + sibling, total); p++) must.add(p);
  const out: (number | string)[] = [];
  let prev = 0;
  for (const p of [...must].sort((a, b) => a - b)) {
    if (p > prev + 1) out.push(ellipsis);
    out.push(p);
    prev = p;
  }
  return out;
}

/** dct's ``_render_pagination_controls``: ``Rows a–b of n`` on the left, ``‹ 1 … 4 5 6 … 12 ›`` right-anchored. */
function Pager({ p, page, total, start, end, n, font, setPage }: { p: Pagination; page: number; total: number; start: number; end: number; n: number; font: Font; setPage: (n: number) => void }) {
  const items: { role: string; glyph: string; target: number }[] = [
    { role: "prev", glyph: p.prev, target: page > 1 ? page - 1 : 0 },
    ...pagerWindow(page, total, p.sibling, p.boundary, p.ellipsis).map((it) => (typeof it === "string" ? { role: "ellipsis", glyph: it, target: 0 } : { role: "page", glyph: String(it), target: it })),
    { role: "next", glyph: p.next, target: page < total ? page + 1 : 0 },
  ];
  return (
    <div className="dcd-pager" style={{ display: "flex", alignItems: "center", justifyContent: "space-between", height: p.control_height, fontFamily: font.family, fontSize: p.font_size }}>
      <span className="dcd-pager-label" style={{ color: p.color_inactive, fontWeight: p.weight_inactive, fontVariantNumeric: "tabular-nums" }}>{`Rows ${start}–${end} of ${n}`}</span>
      <span style={{ display: "flex", alignItems: "center" }}>
        {items.map((it, i) => {
          const active = it.role === "page" && it.target === page;
          const disabled = (it.role === "prev" || it.role === "next") && it.target === 0;
          const clickable = !active && !disabled && it.role !== "ellipsis";
          const color = active || (clickable && it.role !== "page") ? p.color_active : disabled ? p.color_disabled : p.color_inactive;
          const weight = it.role === "prev" || it.role === "next" ? p.weight_chevron : active ? p.weight_active : p.weight_inactive;
          const width = it.role === "page" ? p.item_width : p.item_width * p.aux_slot_ratio;
          return (
            <button
              key={i}
              type="button"
              data-dcd-page={clickable ? it.target : undefined}
              data-dcd-page-role={it.role}
              aria-current={active ? "page" : undefined}
              disabled={!clickable}
              onClick={() => clickable && setPage(it.target)}
              style={{ width, color, fontWeight: weight, background: "none", border: 0, padding: 0, cursor: clickable ? "pointer" : "default", fontFamily: font.family, fontSize: p.font_size, fontVariantNumeric: "tabular-nums" }}
            >
              {it.glyph}
            </button>
          );
        })}
      </span>
    </div>
  );
}

function Table({ t, rows, link, id }: { t: TableSpec; rows: Row[]; link?: string; id: string }) {
  // dct's pagination (``_resolve_visible_rows``): rows exceeding page_rows by at most
  // grow_cap all sit on one page; otherwise page_rows per page with the paginator.
  const P = t.pagination;
  const paged = !!P && rows.length > P.page_rows + P.grow_cap;
  const totalPages = paged && P ? Math.max(1, Math.ceil(rows.length / P.page_rows)) : 1;
  const [pageState, setPage] = useDiveState(`${id}_page`, 1); // dct's page variable name
  const page = Math.min(Math.max(1, Number(pageState) || 1), totalPages);
  const start = paged && P ? (page - 1) * P.page_rows : 0;
  const shown = paged && P ? rows.slice(start, start + P.page_rows) : rows;
  const columns = rows.length ? Object.keys(rows[0]) : t.columns.map((c) => c.key);
  const numeric = (c: Column) => shown.some((r) => typeof r[c.key] === "number");
  const align = (c: Column) => c.align ?? (numeric(c) ? "right" : "left");
  // Shared-scale columns show the magnitude suffix once, on the first non-zero row.
  const anchor: Record<string, number> = {};
  for (const c of t.columns) if (c.shared) anchor[c.key] = Math.max(0, shown.findIndex((r) => typeof r[c.key] === "number" && r[c.key] !== 0));
  // dct's ``symbol_mode: anchors``: the currency prefix and unit suffix appear on the first
  // row only; a magnitude suffix (K/mn/…) carries the value and stays on every row.
  const anchored = (i: number) => t.symbol_mode !== "anchors" || i === 0;
  const cell = (v: unknown, c: Column, i: number): string => {
    if (v == null || v === "") return "—";
    if (c.time && typeof v === "string") return (v.length > 10 ? d3().timeFormat : d3().utcFormat)(c.time)(new Date(v));
    // dct writes a cell that is not a number with Python's own str(), and a bool prints
    // capitalised there (`True`/`False`) — the table shows what dct's table shows.
    if (typeof v === "boolean") return v ? "True" : "False";
    v = asNumber(v);
    if (typeof v !== "number") return String(v);
    if (c.shared) {
      const mag = v !== 0 && (c.shared.repeat || i === anchor[c.key]) ? c.shared.suffix : "";
      const suffix = mag + c.format.suffix;
      const num = d3().format(c.shared.spec)(v / c.shared.divisor);
      return anchored(i) ? c.format.prefix + num + suffix : num + (mag ? suffix : "");
    }
    const [pre, num, suf, mag] = fmt(v, c.format);
    return anchored(i) ? pre + num + suf : num + (mag ? suf : "");
  };
  // dct decides a `bar`'s ceiling and the midline anchor per table column, over the whole
  // dataset (`table._spark_column_layout`); in a Dive that is the rows it just fetched.
  const sparkColumns = useMemo(() => {
    const out: Record<string, { max: number | null; negative: boolean }> = {};
    for (const c of t.columns) {
      if (!c.spark) continue;
      let widest: number | null = null;  // the largest magnitude, which is dct's `bar` ceiling
      let negative = false;
      for (const r of rows) {
        const n = numericCell(r[c.key]);
        if (n === null) continue;
        if (n < 0) negative = true;
        if (widest === null || Math.abs(n) > widest) widest = Math.abs(n);
      }
      out[c.key] = {
        max: c.spark.type === "bar" && c.spark.max == null ? widest : null,
        negative: (c.spark.type === "bar" || c.spark.type === "column") && negative,
      };
    }
    return out;
  }, [rows, t.columns]);
  // dct sizes an in-cell mark from the cell it lands in (`table._render_spark_cell`): the
  // lane width less its padding, capped so the mark always clears the cell edge. An HTML
  // table lays its columns out in the browser, so that width is measured there — and until
  // it has been (a headless render, the first paint), dct's own defaults stand in.
  const sparkKeys = t.columns.filter((c) => c.spark).map((c) => c.key);
  const [cellWidths, setCellWidths] = useState<Record<string, number>>({});
  const cellRefs = useRef<Record<string, HTMLTableCellElement | null>>({});
  const sparkKey = sparkKeys.join("|");
  useEffect(() => {
    const keys = sparkKey ? sparkKey.split("|") : [];
    const measure = () =>
      setCellWidths((prev) => {
        const next: Record<string, number> = {};
        for (const key of keys) {
          const w = cellRefs.current[key]?.clientWidth ?? 0;
          if (w > 0) next[key] = w;
        }
        const same = Object.keys(next).length === Object.keys(prev).length && keys.every((k) => prev[k] === next[k]);
        return same ? prev : next;
      });
    measure();
    if (typeof ResizeObserver === "undefined") return;
    const observer = new ResizeObserver(measure);
    for (const key of keys) {
      const el = cellRefs.current[key];
      if (el) observer.observe(el);
    }
    return () => observer.disconnect();
    // the page too: an HTML table lays its columns out from the rows it is showing, so
    // turning the page can move a lane even though the dataset has not changed.
  }, [sparkKey, rows, page]);
  const sparkWidth = (spark: SparkPlan, key: string) => {
    const cell = cellWidths[key] ?? 0;
    const narrow = spark.type === "column"; // a column is a fixed narrow mark, not a lane-filler
    const fallback = narrow ? (t.spark?.column_width ?? SPARK_WIDTH) : spark.type.startsWith("bar") ? SPARK_BAR_WIDTH : SPARK_WIDTH;
    const wanted = spark.width ?? (narrow || !cell ? fallback : Math.trunc(cell - 16));
    return cell ? Math.min(wanted, Math.trunc(cell - 8)) : wanted;
  };
  const pad = `0 ${t.cell_padding}px`;
  return (
    <div style={{ overflowX: "auto", background: t.background ?? undefined }}>
      {(t.title || t.subtitle) && (
        // dct's title row: the title sits at the top of a title_row.height band, the header follows.
        <div style={{ height: t.title_height, display: "flex", flexDirection: "column", justifyContent: "flex-start" }}>
          {t.title && <div style={{ ...css(t.title_font), lineHeight: 1.1 }}>{t.title}</div>}
          {t.subtitle && <div style={css(t.subtitle_font)}>{t.subtitle}</div>}
        </div>
      )}
      <table style={{ width: "100%", borderCollapse: "collapse", ...css(t.font) }}>
        {t.header.visible && (
          <thead>
            <tr style={{ height: t.header.height, background: t.header.background ?? undefined }}>
              {t.columns.map((c) => (
                <th key={c.key} style={{ ...css(t.header.font), textAlign: align(c), padding: pad, whiteSpace: "nowrap", borderBottom: `${t.header.rule}px solid ${t.rule_color}` }}>
                  {c.header_link ? <Anchor href={c.header_link} color={t.link_color}>{c.label}</Anchor> : c.label}
                </th>
              ))}
            </tr>
          </thead>
        )}
        <tbody>
          {shown.map((r, i) => {
            // dct's whole-row link band (table.py): every cell without its own link opens it
            const rowHref = link ? resolveCellLink(link, r, columns) : null;
            return (
              <tr key={i} data-dcd-row-href={rowHref ?? undefined} style={{ height: t.row.height, background: i % 2 === 1 && t.row.stripe ? t.row.stripe : undefined }}>
                {t.columns.map((c) => {
                  const v = r[c.key];
                  const cellHref = c.link ? resolveCellLink(c.link, r, columns) : null;
                  const mark = c.spark && t.spark && v != null ? sparkMark({ plan: c.spark, theme: t.spark, value: v, column: sparkColumns[c.key], width: sparkWidth(c.spark, c.key) }) : null;
                  const content =
                    mark !== null ? (
                      // The mark is taken out of flow: an HTML table sizes a lane from its
                      // content, so a mark drawn at the width of the lane it was measured
                      // in would feed its own size back into that measurement. dct decides
                      // the lane before it draws, and centres a `column` on the lane's
                      // midpoint (`_render_data_rows`) while every other mark sits at the
                      // left edge.
                      <div style={{ position: "relative", width: "100%", height: c.spark!.height }}>
                        <div style={{ position: "absolute", top: 0, ...(c.spark!.type === "column" ? { left: "50%", transform: "translateX(-50%)" } : { left: 0 }) }}>{mark}</div>
                      </div>
                    ) : c.swatch && typeof v === "string" ? (
                      <span style={{ display: "inline-block", width: 10, height: 10, background: v, borderRadius: 2 }} />
                    ) : (
                      cell(v, c, i)
                    );
                  return (
                    <td
                      key={c.key}
                      ref={i === 0 && c.spark ? (el) => void (cellRefs.current[c.key] = el) : undefined}
                      style={{
                        textAlign: align(c),
                        padding: pad,
                        whiteSpace: "nowrap",
                        fontFamily: typeof v === "number" ? t.numeric_font : undefined,
                        borderBottom: t.row.rule ? `${t.row.rule}px solid ${t.rule_color}` : undefined,
                        color: cellHref ? t.link_color : undefined,
                      }}
                    >
                      {cellHref ? <Anchor href={cellHref} color={t.link_color} className="dcd-cell-link">{content}</Anchor> : rowHref ? <Anchor href={rowHref} className="dcd-row-link">{content}</Anchor> : content}
                    </td>
                  );
                })}
              </tr>
            );
          })}
        </tbody>
      </table>
      {paged && P && <Pager p={P} page={page} total={totalPages} start={start + 1} end={start + shown.length} n={rows.length} font={t.font} setPage={setPage} />}
      {rows.length === 0 && <div style={{ ...css(t.empty_font), color: MANIFEST.style.muted, textAlign: "center", padding: t.cell_padding }}>No data</div>}
    </div>
  );
}

function Chart({ entry, results, ready }: { entry: ChartEntry; results: Results; ready: boolean }) {
  if (entry.kind === "svg") return <Svg html={entry.svg ?? ""} />;
  if (entry.kind === "unsupported") return <ErrorBox message={entry.message ?? `${entry.type} '${entry.id}' could not be compiled`} />;
  const q = entry.query ? results[entry.query] : undefined;
  const rows = entry.query ? q?.rows ?? null : entry.snapshot ?? [];
  const P = entry.pad;
  const padding = P ? `${P.top}px ${P.right}px ${P.bottom}px ${P.left}px` : undefined;
  if (q?.error) return <div style={{ minWidth: 0, padding }}><ErrorBox message={q.error} /></div>;
  if (!ready || !rows || q?.loading) return <div style={{ minWidth: 0, padding }}><div className="animate-pulse rounded bg-gray-100" style={{ height: entry.height }} /></div>;
  if (entry.kind === "vega")
    // dct compiled the card padding into the Vega spec (additive_padding): the SVG is the
    // whole card and must not be padded again; only the attached legend table needs it.
    return (
      <div style={{ minWidth: 0 }}>
        <VegaChart entry={entry} rows={rows} />
        {entry.legend && <div style={{ padding }}><Table t={entry.legend.table} rows={entry.legend.rows} id={entry.id + "_legend"} /></div>}
      </div>
    );
  if (entry.kind === "spark_bar") return <div style={{ minWidth: 0, padding }}><SparkBar s={entry.spark_bar!} rows={rows} /></div>;
  return <div style={{ minWidth: 0, padding }}>{entry.kind === "kpi" ? <Kpi k={entry.kpi!} rows={rows} link={entry.link} /> : <Table t={entry.table!} rows={rows} link={entry.link} id={entry.id} />}</div>;
}

// ─────────────────────────────────────────────────────────────────────────────
// Variables bar — dct's controls strip, from its resolved controls
// ─────────────────────────────────────────────────────────────────────────────
type Setter = (v: unknown) => void;

function useDraft(value: string) {
  const [draft, setDraft] = useState(value);
  useEffect(() => setDraft(value), [value]);
  return [draft, setDraft] as const;
}

function ControlView({ c, value: bound, set: commit, enabled }: { c: Control; value: unknown; set: Setter; enabled: boolean }) {
  const V = MANIFEST.style.variables;
  // The bound value arrives one render after a commit (the binding reports through an
  // effect); the control itself reflects a change at once.
  const [value, setLocal] = useState(bound);
  useEffect(() => setLocal(bound), [bound]);
  const set: Setter = (v) => {
    setLocal(v);
    commit(v);
  };
  const field: CSSProperties = {
    height: V.input.height,
    background: V.input.background,
    padding: `${V.input.padding.top}px ${V.input.padding.right}px ${V.input.padding.bottom}px ${V.input.padding.left}px`,
    borderRadius: V.input.radius,
    border: `1px solid ${MANIFEST.style.border_color}`,
    boxSizing: "border-box",
    ...css(V.value_font),
  };
  const t = c.input;
  let input: ReactNode;
  if (t === "select" || t === "radio") {
    input = (
      <select value={isUnset(value) ? "" : String(value)} disabled={!enabled} onChange={(e) => set(e.target.value === "" ? null : e.target.value)} style={{ ...field, minWidth: V.input.widths.number }}>
        {(c.can_unset || isUnset(value)) && <option value="">{c.unset_label}</option>}
        {c.options.map((o) => <option key={o} value={o}>{o}</option>)}
      </select>
    );
  } else if (t === "multiselect") {
    input = <MultiSelect c={c} value={Array.isArray(value) ? value.map(String) : isUnset(value) ? [] : [String(value)]} set={set} enabled={enabled} field={field} />;
  } else if (t === "checkbox") {
    input = <input type="checkbox" checked={value === true || value === "true"} disabled={!enabled} onChange={(e) => set(e.target.checked)} style={{ width: V.input.widths.checkbox, height: V.input.widths.checkbox }} />;
  } else if (t === "slider" || t === "range") {
    input = <Slider c={c} value={typeof value === "number" ? value : Number(value ?? c.min ?? 0)} set={set} enabled={enabled} />;
  } else if (t === "date" || t === "datepicker") {
    input = <input type="date" value={isUnset(value) ? "" : String(value).slice(0, 10)} disabled={!enabled} onChange={(e) => set(e.target.value || null)} style={field} />;
  } else if (t === "daterange") {
    const [s, e] = Array.isArray(value) && value.length === 2 ? value.map((x) => (x == null ? "" : String(x).slice(0, 10))) : ["", ""];
    return (
      <div data-dcd-var={c.key} data-dcd-input={t} style={{ display: "flex", alignItems: "center", gap: V.control_gap, opacity: enabled ? 1 : 0.55 }}>
        <label style={css(V.label_font)}>{c.label}:</label>
        <input type="date" data-dcd-range="start" value={s} disabled={!enabled} onChange={(ev) => set([ev.target.value, e])} style={field} />
        <span style={css(V.value_font)}>–</span>
        <input type="date" data-dcd-range="end" value={e} disabled={!enabled} onChange={(ev) => set([s, ev.target.value])} style={field} />
      </div>
    );
  } else {
    input = <TextEntry c={c} value={isUnset(value) ? "" : String(value)} set={set} enabled={enabled} field={field} number={t === "number"} />;
  }
  return (
    <div data-dcd-var={c.key} data-dcd-input={t} style={{ display: "flex", alignItems: "center", gap: V.control_gap, opacity: enabled ? 1 : 0.55 }}>
      <label style={css(V.label_font)}>{c.label}:</label>
      {input}
    </div>
  );
}

/** Commits on Enter / blur, like dct's lifted text and number inputs. */
function TextEntry({ c, value, set, enabled, field, number }: { c: Control; value: string; set: Setter; enabled: boolean; field: CSSProperties; number: boolean }) {
  const V = MANIFEST.style.variables;
  const [draft, setDraft] = useDraft(value);
  const commit = () => {
    if (draft === value) return;
    if (draft === "") return set(null);
    set(number ? Number(draft) : draft);
  };
  return (
    <input
      type={number ? "number" : "text"}
      value={draft}
      placeholder={c.placeholder || undefined}
      disabled={!enabled}
      min={number ? c.min ?? undefined : undefined}
      max={number ? c.max ?? undefined : undefined}
      step={number ? c.step ?? undefined : undefined}
      onChange={(e) => setDraft(e.target.value)}
      onBlur={commit}
      onKeyDown={(e) => e.key === "Enter" && (e.target as HTMLInputElement).blur()}
      style={{ ...field, width: number ? V.input.widths.number : V.input.widths.text }}
    />
  );
}

/** Commits on release, like dct's slider (the value beside the track follows the thumb). */
function Slider({ c, value, set, enabled }: { c: Control; value: number; set: Setter; enabled: boolean }) {
  const V = MANIFEST.style.variables;
  const [draft, setDraft] = useState(value);
  useEffect(() => setDraft(value), [value]);
  const commit = () => draft !== value && set(draft);
  return (
    <>
      <input type="range" min={c.min ?? 0} max={c.max ?? 100} step={c.step ?? 1} value={draft} disabled={!enabled} onChange={(e) => setDraft(Number(e.target.value))} onPointerUp={commit} onKeyUp={commit} onBlur={commit} style={{ width: V.input.widths.range }} />
      <span data-dcd-slider-value style={{ ...css(V.value_font), minWidth: 30 }}>{draft}</span>
    </>
  );
}

/** dct's multiselect popover: a listbox of members, an unset row when the control can be cleared. */
function MultiSelect({ c, value, set, enabled, field }: { c: Control; value: string[]; set: Setter; enabled: boolean; field: CSSProperties }) {
  const V = MANIFEST.style.variables;
  const [open, setOpen] = useState(false);
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => {
    if (!open) return;
    const onDoc = (e: MouseEvent) => !ref.current?.contains(e.target as Node) && setOpen(false);
    document.addEventListener("mousedown", onDoc);
    return () => document.removeEventListener("mousedown", onDoc);
  }, [open]);
  const toggle = (o: string) => set(value.includes(o) ? value.filter((x) => x !== o) : c.options.filter((x) => x === o || value.includes(x)));
  return (
    <div ref={ref} style={{ position: "relative" }}>
      <button type="button" aria-haspopup="listbox" aria-expanded={open} disabled={!enabled} onClick={() => setOpen(!open)} style={{ ...field, display: "flex", alignItems: "center", gap: 6, cursor: "pointer" }}>
        <span style={{ color: value.length ? undefined : V.placeholder_color ?? undefined }}>{value.length ? value.join(", ") : c.unset_label}</span>
        <span aria-hidden style={{ color: V.placeholder_color ?? undefined }}>▾</span>
      </button>
      {open && (
        <div role="listbox" aria-multiselectable style={{ position: "absolute", top: "100%", left: 0, zIndex: 20, marginTop: 2, minWidth: "100%", background: MANIFEST.style.background, border: `1px solid ${MANIFEST.style.border_color}`, borderRadius: V.input.radius, padding: 4, boxShadow: "0 6px 16px rgba(15,23,42,0.12)", ...css(V.value_font) }}>
          {c.can_unset && (
            <div role="option" data-unset aria-selected={value.length === 0} onClick={() => set([])} style={{ padding: "4px 8px", cursor: "pointer", whiteSpace: "nowrap", fontWeight: value.length === 0 ? 600 : undefined }}>
              {c.unset_label}
            </div>
          )}
          {c.options.map((o) => (
            <label key={o} role="option" data-value={o} aria-selected={value.includes(o)} style={{ display: "flex", alignItems: "center", gap: 6, padding: "4px 8px", cursor: "pointer", whiteSpace: "nowrap" }}>
              <input type="checkbox" checked={value.includes(o)} onChange={() => toggle(o)} />
              {o}
            </label>
          ))}
        </div>
      )}
    </div>
  );
}

function VariablesBar({ controls, notes, values, setters }: { controls: Control[]; notes: string[]; values: Values; setters: Record<string, Setter> }) {
  const V = MANIFEST.style.variables;
  if (!controls.length && !notes.length) return null;
  return (
    <div className="dcd-variables" style={{ display: "flex", flexWrap: "wrap", alignItems: "center", gap: V.gap, minHeight: V.container_height, padding: `0 ${MANIFEST.style.card_padding}px`, ...css(V.font) }}>
      {controls.map((c) => (
        <ControlView key={c.key} c={c} value={values[c.key]} set={setters[c.key] ?? (() => undefined)} enabled={condValue(c.enabled, values)} />
      ))}
      {notes.length > 0 && (
        <div className="dcd-variable-notes text-xs" style={{ color: MANIFEST.style.muted, flexBasis: "100%" }} title={notes.join("\n")}>
          Some controls run with the board defaults in this Dive: {notes.join(" · ")}
        </div>
      )}
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// Layout — dct sized every slot; cols/grid bands arrive as CSS grid tracks
// ─────────────────────────────────────────────────────────────────────────────
type Ctx = { results: Results; ready: boolean; values: Values; setters: Record<string, Setter> };

function Tabs({ node, ctx }: { node: LayoutNode; ctx: Ctx }) {
  const T = MANIFEST.style.tabs;
  const slugs = node.slugs ?? node.items.map((_, i) => `tab_${i}`);
  const [slug, setSlug] = useDiveState(node.key ?? "_tab", slugs[node.default ?? 0]); // dct's tab variable
  const idx = Math.max(0, slugs.indexOf(String(slug)));
  const left = node.position === "left";
  const bar = (
    <div role="tablist" style={{ display: "flex", flexDirection: left ? "column" : "row", height: left ? undefined : T.height, alignItems: left ? "stretch" : "center", marginBottom: left ? 0 : node.gap, marginRight: left ? node.gap : 0 }}>
      {(node.titles ?? []).map((title, i) => (
        <button
          key={i}
          type="button"
          role="tab"
          data-dcd-tab={slugs[i]}
          aria-selected={i === idx}
          onClick={() => setSlug(slugs[i])}
          className={left ? "px-3 py-2 text-left" : "flex-1 px-3"}
          style={{
            ...css(T.font),
            height: left ? T.height : "100%",
            fontWeight: i === idx ? T.active_weight : T.inactive_weight,
            color: i === idx ? T.active_color : T.inactive_color,
            background: (i === idx ? T.active_fill : T.inactive_fill) ?? "transparent",
            border: T.border.width ? `${T.border.width}px solid ${T.border.color}` : 0,
            borderRadius: T.border.radius,
          }}
        >
          {title}
        </button>
      ))}
    </div>
  );
  return (
    <div style={{ display: "flex", flexDirection: left ? "row" : "column" }}>
      {bar}
      <div style={{ flex: 1, minWidth: 0 }}>{renderItem(node.items[Math.min(idx, node.items.length - 1)], idx, ctx)}</div>
    </div>
  );
}

/** dct's ``details:`` section (rendering.py): a summary bar; the content only when expanded. */
function DetailsSection({ d, children }: { d: Details; children: ReactNode }) {
  const D = MANIFEST.style.details;
  const [state, setState] = useDiveState(d.key, d.expanded); // dct's hidden checkbox variable
  const expanded = state === true || state === "true";
  return (
    <section data-dcd-details={d.key} data-expanded={expanded} style={{ border: D.border.width ? `${D.border.width}px solid ${D.border.color}` : undefined, borderRadius: D.border.radius }}>
      <button
        type="button"
        aria-expanded={expanded}
        onClick={() => setState(!expanded)}
        style={{
          display: "flex", alignItems: "center", width: "100%", height: D.summary_height, textAlign: "left", cursor: "pointer",
          background: (expanded ? D.expanded_fill : D.collapsed_fill) ?? "transparent", border: 0, borderRadius: D.border.radius, color: D.color, padding: 0,
        }}
      >
        <span aria-hidden style={{ position: "absolute", marginLeft: D.arrow_x, fontSize: D.arrow_size }}>{expanded ? "▼" : "▶"}</span>
        <span style={{ marginLeft: D.label_x, ...css(D.font), color: D.color, fontWeight: 500 }}>{expanded ? d.expanded_summary : d.summary}</span>
      </button>
      {expanded && <div style={{ marginTop: D.content_y_offset }}>{children}</div>}
    </section>
  );
}

function renderItem(it: LayoutItem | null, i: number, ctx: Ctx): ReactNode {
  if (!it) return null;
  if (!condValue(it.visible, ctx.values)) return null; // dct: a hidden item costs nothing
  if ("chart" in it) return <Chart key={i} entry={MANIFEST.charts[it.chart]} results={ctx.results} ready={ctx.ready} />;
  const board = <Board key={i} node={it.board} ctx={ctx} />;
  return it.details ? <DetailsSection key={i} d={it.details}>{board}</DetailsSection> : board;
}

function Layout({ node, ctx }: { node: LayoutNode; ctx: Ctx }) {
  if (node.type === "tabs") return <Tabs node={node} ctx={ctx} />;
  if (node.type === "cols") return <div style={{ display: "grid", gridTemplateColumns: node.columns, gap: node.gap }}>{node.items.map((it, i) => renderItem(it, i, ctx))}</div>;
  return <div style={{ display: "flex", flexDirection: "column", gap: node.gap }}>{node.items.map((it, i) => renderItem(it, i, ctx))}</div>;
}

function Board({ node, ctx }: { node: BoardNode; ctx: Ctx }) {
  const S = MANIFEST.style;
  return (
    <section style={{ display: "flex", flexDirection: "column", gap: S.gap }}>
      {(node.title_svg || node.text_svg) && (
        <header style={{ padding: `0 ${S.card_padding}px` }}>
          <Svg html={node.title_svg} />
          <Svg html={node.text_svg} />
        </header>
      )}
      <VariablesBar controls={node.variables ?? []} notes={node.variable_notes ?? []} values={ctx.values} setters={ctx.setters} />
      <Layout node={node.layout} ctx={ctx} />
    </section>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// Dive
// ─────────────────────────────────────────────────────────────────────────────
export default function DbtChartsDive() {
  const [results, setResults] = useState<Results>({});
  const onChange = (name: string, s: QueryState) => setResults((prev) => ({ ...prev, [name]: s }));
  const [bindings, setBindings] = useState<Record<string, { value: unknown; set: Setter }>>({});
  const onBind = (key: string, value: unknown, set: Setter) => setBindings((prev) => ({ ...prev, [key]: { value, set } }));
  const values = useMemo<Values>(() => ({ ...DEFAULTS, ...Object.fromEntries(Object.entries(bindings).map(([k, b]) => [k, b.value])) }), [bindings]);
  const setters = useMemo(() => Object.fromEntries(Object.entries(bindings).map(([k, b]) => [k, b.set])), [bindings]);
  const bound = CONTROLS.every((c) => c.key in bindings);
  // Only the queries whose SQL changed re-run: useSQLQuery keys on the SQL text.
  const sqls = useMemo(() => Object.fromEntries(Object.keys(MANIFEST.queries).map((q) => [q, sqlFor(q, values)])), [values]);
  const vega = useVega();
  const S = MANIFEST.style;
  const ctx: Ctx = { results, ready: vega.ready, values, setters };
  return (
    // The Dive sandbox iframe has a fixed height; make the board itself the scroll container so
    // tall boards can always be scrolled, whatever the host document's overflow rules are.
    <main style={{ background: S.background, height: "100vh", overflowY: "auto", boxSizing: "border-box", padding: S.page_padding, ...css(S.font) }}>
      <style>{".dcd-svg>svg{display:block;max-width:100%;height:auto}"}</style>
      {CONTROLS.map((c) => (
        <VariableBinding key={c.key} control={c} onBind={onBind} />
      ))}
      {bound && Object.entries(sqls).map(([name, sql]) => <QueryLoader key={name} name={name} sql={sql} onChange={onChange} />)}
      {vega.error ? <ErrorBox message={`Could not load the Vega bundle: ${vega.error}`} /> : <Board node={MANIFEST.board} ctx={ctx} />}
      <footer className="mt-8 text-xs" style={{ color: S.muted }}>
        dbt Charts board compiled by dbt_charts_dive · built {MANIFEST.built_at} · Vega-Lite {MANIFEST.bundle.vega_lite} · Vega {MANIFEST.bundle.vega} · vega-embed {MANIFEST.bundle.vega_embed}
      </footer>
    </main>
  );
}
