// AUTO-GENERATED by dive/bundle.mjs — do not edit. Source: dive/.dive-preview/src/*
import { useState, useMemo } from "react";
import { useSQLQuery, useDiveState } from "@motherduck/react-sql-query";
import { BarChart, Bar, XAxis, YAxis, ReferenceLine, LabelList, ResponsiveContainer } from "recharts";
import { Loader2 } from "lucide-react";

// ───────── lib.tsx ─────────
/* lib — shared tokens + atoms for the "Malloy vs Context" dive.
   Tufte-inspired data-journalism: high data-ink, restrained palette (grays + two
   arm colors), serif prose, mono numerals, direct labels, reference lines, captions. */

const N = (v: unknown): number => (v != null ? Number(v) : 0);
const rows = (d: unknown): any[] => (Array.isArray(d) ? d : []);
const pct = (v: unknown) => `${N(v).toFixed(1)}%`;
// Escape a value for use inside a single-quoted SQL literal.
const esc = (v: unknown) => String(v ?? "").replace(/'/g, "''");

const STORY = `"agentic_malloy_story"."main"`;
const LOGS = `"agentic_malloy_logs"."main"`;

// Ink: near-black text, two muted grays, hairline rule. Color is reserved for data.
const INK = {
  text: "#222222", muted: "#6f6f6f", faint: "#9a9a9a",
  rule: "#e3e0d8", bg: "#f6f4ee", paper: "#ffffff", panel: "#fbfaf6",
};
// The only saturated inks: the two substrates, and the three answer paths.
const ARM = { baseline: "#2d6a2d", malloy: "#0a6aa8" };
const PATH = { sql: "#b0521f", malloy: "#0a6aa8", other: "#b8b4a8" };

const SERIF = 'Georgia, "Iowan Old Style", Charter, "Palatino Linotype", Palatino, serif';
const SANS = 'system-ui, -apple-system, "Segoe UI", Roboto, Helvetica, sans-serif';
const MONO = 'ui-monospace, SFMono-Regular, Menlo, Monaco, "Roboto Mono", Consolas, monospace';

// Shared run-label constants (used across tabs — defined once to avoid bundle collisions).
const OFFICIAL = "Malloy · sonnet+opus · official";
const PREFIX = "Malloy · sonnet+opus · official (pre-fix)";
const CONTROLLED = "Malloy · gemini · controlled (low)";
// Shared <select> style.
const sel: React.CSSProperties = { fontFamily: SANS, fontSize: 12.5, padding: "3px 8px", border: `1px solid ${INK.rule}`, borderRadius: 4, background: INK.paper, color: INK.text };

const TABS = [
  { key: "story", label: "The story" },
  { key: "metrics", label: "Metrics & misses" },
  { key: "build", label: "Harness & prompts" },
  { key: "layer", label: "The layer" },
  { key: "traces", label: "Agent traces" },
];

/* Plain-language gloss for the run-label jargon — surfaced as hover tooltips. */
function noteFor(label: string): string {
  if (label.includes("Baseline")) return "The tuned markdown+SQL context layer — the thing Malloy is measured against.";
  if (label.includes("pre-fix")) return "An earlier official run, before the skill fixes (answer-format rules + a clean SQL fallback) that raised it from 88.3% to 91.2%.";
  if (label.includes("controlled")) return "The clean same-model control: gemini on both arms, so only the substrate differs.";
  if (label.includes("new-harness")) return "Harness with a one-call view catalog, a SQL fallback, and deterministic linting. 'high' = more model reasoning.";
  if (label.includes("official")) return "The canonical config behind the claim: a mid-tier model authors, a stronger model fixes errors, on the model-authored layer, no in-place steering.";
  return "";
}

/* Inline glossed term: dotted underline + an instant styled popover (native title is
   unreliable — delayed, and flaky on SVG). */
function Tip({ text, children }: { text: string; children: React.ReactNode }) {
  const [show, setShow] = useState(false);
  if (!text) return <>{children}</>;
  return (
    <span style={{ position: "relative", display: "inline-block", borderBottom: `1px dotted ${INK.faint}`, cursor: "help" }}
      onMouseEnter={() => setShow(true)} onMouseLeave={() => setShow(false)}>
      {children}
      {show ? (
        <span style={{ position: "absolute", bottom: "135%", left: 0, zIndex: 60, width: 250, background: INK.text, color: "#fff",
          fontFamily: SANS, fontSize: 11.5, fontWeight: 400, fontStyle: "normal", lineHeight: 1.45, padding: "7px 10px",
          borderRadius: 6, boxShadow: "0 6px 18px rgba(0,0,0,0.2)", whiteSpace: "normal" }}>{text}</span>
      ) : null}
    </span>
  );
}

/* Editorial intro paragraph. */
function Lede({ children }: { children: React.ReactNode }) {
  return <p style={{ fontFamily: SERIF, fontSize: 17, lineHeight: 1.55, color: INK.text, margin: "0 0 14px" }}>{children}</p>;
}

/* A figure wrapper with an italic caption beneath — the data-journalism unit. */
function Figure({ children, caption }: { children: React.ReactNode; caption: React.ReactNode }) {
  return (
    <figure style={{ margin: "0 0 22px" }}>
      {children}
      <figcaption style={{ fontFamily: SERIF, fontStyle: "italic", fontSize: 12.5, color: INK.muted, marginTop: 7, lineHeight: 1.45 }}>{caption}</figcaption>
    </figure>
  );
}

/* A restrained KPI: big mono numeral, small label, optional sub. */
function Stat({ value, label, color, sub }: { value: string; label: string; color?: string; sub?: string }) {
  return (
    <div>
      <div style={{ fontFamily: MONO, fontSize: 34, fontWeight: 600, color: color ?? INK.text, lineHeight: 1.05, letterSpacing: "-0.02em" }}>{value}</div>
      <div style={{ fontSize: 12.5, color: INK.muted, marginTop: 3 }}>{label}</div>
      {sub ? <div style={{ fontSize: 11, color: INK.faint, marginTop: 1 }}>{sub}</div> : null}
    </div>
  );
}

/* Inline horizontal bar inside a table cell (bar-in-table). value drawn as a fill;
   the number sits right-aligned on top. max scales the fill. */
function BarCell({ value, max = 100, color = INK.text, label }: { value: number; max?: number; color?: string; label?: string }) {
  const w = Math.max(0, Math.min(100, (value / max) * 100));
  return (
    <div style={{ position: "relative", height: 18, minWidth: 90 }}>
      <div style={{ position: "absolute", left: 0, top: 3, height: 12, width: `${w}%`, background: color, opacity: 0.18, borderRadius: 1 }} />
      <div style={{ position: "absolute", right: 4, top: 0, fontFamily: MONO, fontSize: 12, color: INK.text }}>{label ?? value}</div>
    </div>
  );
}

function Dot({ color, children }: { color: string; children: React.ReactNode }) {
  return (
    <span style={{ display: "inline-flex", alignItems: "center", gap: 5, fontSize: 12, color: INK.muted, marginRight: 12 }}>
      <span style={{ width: 9, height: 9, background: color, borderRadius: 2, display: "inline-block" }} />{children}
    </span>
  );
}

function Rule() { return <div style={{ borderTop: `1px solid ${INK.rule}`, margin: "26px 0" }} />; }

function Skel({ h = 16, w = "60%" }: { h?: number; w?: number | string }) {
  return <div className="animate-pulse" style={{ height: h, width: w, background: "#eceae3", borderRadius: 3 }} />;
}
function Loading({ label }: { label: string }) {
  return <div style={{ display: "flex", alignItems: "center", gap: 8, color: INK.muted, fontSize: 13, padding: "10px 0", fontFamily: SANS }}><Loader2 className="animate-spin" size={14} /> {label}</div>;
}

/* Section header — small serif kicker + rule. */
function Head({ kicker, title, children }: { kicker?: string; title: string; children?: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 14 }}>
      {kicker ? <div style={{ fontFamily: SANS, fontSize: 11, letterSpacing: "0.08em", textTransform: "uppercase", color: INK.faint, marginBottom: 4 }}>{kicker}</div> : null}
      <h2 style={{ fontFamily: SERIF, fontSize: 21, fontWeight: 600, color: INK.text, margin: 0 }}>{title}</h2>
      {children ? <p style={{ fontFamily: SERIF, fontSize: 14, color: INK.muted, marginTop: 6, lineHeight: 1.5, fontStyle: "italic" }}>{children}</p> : null}
    </div>
  );
}

/* table cell styles */
const td: React.CSSProperties = { padding: "5px 10px", fontSize: 12.5, borderBottom: `1px solid ${INK.rule}`, textAlign: "right", fontFamily: MONO, color: INK.text };
const tdL: React.CSSProperties = { ...td, textAlign: "left", fontFamily: SANS };
const th: React.CSSProperties = { padding: "4px 10px", fontSize: 10.5, letterSpacing: "0.04em", textTransform: "uppercase", color: INK.faint, fontWeight: 500, borderBottom: `1px solid ${INK.faint}`, fontFamily: SANS };
const thL: React.CSSProperties = { ...th, textAlign: "left" };


// ───────── StoryTab.tsx ─────────

const APATH = { view: "#0a6aa8", authored: "#7ba6c4", sql: "#b0521f", other: "#cfcabb" };

function Chapter({ n, title, children }: { n: number; title: string; children: React.ReactNode }) {
  return (
    <section style={{ marginBottom: 32 }}>
      <div style={{ display: "flex", alignItems: "baseline", gap: 12, marginBottom: 9 }}>
        <span style={{ fontFamily: MONO, fontSize: 13, color: INK.faint }}>{String(n).padStart(2, "0")}</span>
        <h2 style={{ fontFamily: SERIF, fontSize: 25, fontWeight: 600, color: INK.text, margin: 0, letterSpacing: "-0.01em" }}>{title}</h2>
      </div>
      <div style={{ fontFamily: SERIF, fontSize: 15, color: INK.text, lineHeight: 1.6 }}>{children}</div>
    </section>
  );
}
const RUN_KEY = [
  ["official", "the canonical config behind the claim"],
  ["pre-fix", "before the skill fixes (raised it 88.3→91.2%)"],
  ["new-harness", "view-catalog + SQL fallback + linting"],
  ["controlled", "same-model baseline comparison"],
];

function StoryTab() {
  const [, setTab] = useDiveState<string>("tab", "story");
  const [, setAci] = useDiveState<string>("aci_task", "1443");
  const [, setTraceRun] = useDiveState<string>("trace_run", OFFICIAL);
  const [, setTraceTask] = useDiveState<string>("trace_task", "1443");
  const go = (tab: string, fn?: () => void) => () => { if (fn) fn(); setTab(tab); };
  const Link = ({ onClick, children }: { onClick: () => void; children: React.ReactNode }) => (
    <button onClick={onClick} style={{ background: "none", border: "none", padding: 0, cursor: "pointer", color: ARM.malloy, fontFamily: SANS, fontSize: 13, fontWeight: 600, borderBottom: `1px solid ${ARM.malloy}55` }}>{children} →</button>
  );

  const runsQ = useSQLQuery(`SELECT run_label, arm, acc_pct, median_prompt_tokens AS tok, pct_sql, controlled_pair FROM "agentic_malloy_story"."main"."runs" WHERE split='test' ORDER BY acc_pct DESC, run_label`);
  const aciQ = useSQLQuery(`SELECT r.run_label, count(*) AS n, sum(r.is_correct::int) AS correct
    FROM "agentic_malloy_story"."main"."results" r JOIN "agentic_malloy_story"."main"."tasks" t USING (task_id)
    WHERE t.family='aci_most_expensive_template' AND r.run_label IN ('Baseline · markdown+SQL (gemini)','${OFFICIAL}','${PREFIX}') GROUP BY r.run_label`);
  const pathQ = useSQLQuery(`SELECT answer_path, count(*) AS n FROM "agentic_malloy_story"."main"."results" WHERE run_label='${OFFICIAL}' GROUP BY answer_path`);

  const rr = rows(runsQ.data);
  const baseline = rr.find((r) => r.arm === "baseline");
  const malloy = rr.filter((r) => r.arm === "malloy");
  // "Best" is the official run everywhere this tab cites it (accuracy stat, SQL-share
  // finding, chapter-6 path split all describe OFFICIAL) — don't let a reordering of
  // acc_pct silently make the stat and the path counts describe different runs.
  const best = malloy.find((r) => r.run_label === OFFICIAL) ?? malloy[0];
  const ctrlB = rr.find((r) => r.controlled_pair && r.arm === "baseline");
  const ctrlM = rr.find((r) => r.controlled_pair && r.arm === "malloy");
  const tokMult = ctrlB && ctrlM ? N(ctrlM.tok) / N(ctrlB.tok) : 0;
  const officialSql = best ? N(best.pct_sql) : 0;
  // Stable identity: recharts restarts its entry animation whenever the data prop
  // changes identity, and this tab re-renders several times while aciQ/pathQ resolve.
  const chart = useMemo(
    () => rows(runsQ.data).filter((r) => r.arm === "malloy").map((r) => ({ label: String(r.run_label).replace("Malloy · ", ""), acc: N(r.acc_pct) })),
    [runsQ.data],
  );
  const aci = rows(aciQ.data);
  const aBase = aci.find((r) => String(r.run_label).includes("Baseline"));
  const aView = aci.find((r) => String(r.run_label).includes("pre-fix"));
  const aSql = aci.find((r) => String(r.run_label).endsWith("official"));
  const pr = rows(pathQ.data); const pN = (k: string) => N(pr.find((r) => r.answer_path === k)?.n);
  const pTot = pr.reduce((s, r) => s + N(r.n), 0) || 1;

  return (
    <div>
      <Chapter n={1} title="The thesis">
        <Lede>A semantic layer is supposed to be the clean way to hand an analytics agent its definitions —
          one source of truth per metric, governed and queryable. I wanted to know whether that actually
          helps the agent, or just feels tidy to us.</Lede>
        <p>So I ran the experiment: a <b>Malloy semantic layer</b> head-to-head against a tuned
          <b> markdown + SQL context layer</b> on <b>DABstep</b> — 26 training questions, 419 held out. The bar
          is a conjunction — the layer has to win on tokens <i>and</i> not lose accuracy. Same model, same
          scorer, same data. The only thing that changes is the substrate the agent reads from.</p>
      </Chapter>

      <Chapter n={2} title="What I tested">
        <p>Both arms explore the data with SQL on MotherDuck. The difference is the final answer: the baseline
          submits SQL, the Malloy arm submits compiled Malloy. That’s the only knob I turned.</p>
        <div style={{ display: "flex", gap: 14, margin: "12px 0", flexWrap: "wrap" }}>
          {[["Baseline", ARM.baseline, "Markdown context items + SQL patterns the agent adapts per question."],
            ["Treatment", ARM.malloy, "A model-authored Malloy layer: one source per entity, joins, views."]].map(([t, c, d]) => (
            <div key={t as string} style={{ flex: "1 1 240px", borderTop: `2px solid ${c as string}`, paddingTop: 8 }}>
              <div style={{ fontFamily: SANS, fontWeight: 700, color: c as string, fontSize: 13 }}>{t}</div>
              <div style={{ fontFamily: SERIF, fontSize: 13.5, color: INK.muted, marginTop: 3, lineHeight: 1.5 }}>{d}</div>
            </div>
          ))}
        </div>
        <p style={{ fontSize: 13.5, color: INK.muted }}><b style={{ color: INK.text }}>A model wrote the layer, not me</b> —
          it read the manual, the 26 Q/A, and the schema, authored the Malloy, cleared a compile-and-execute gate and a
          repair loop, then had its provenance locked. So before you ask: I didn’t hand-tune Malloy to lose. This is not
          a “bad Malloy” story. <Link onClick={go("build")}>how the layer was built</Link></p>
      </Chapter>

      <Chapter n={3} title="The result">
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(140px,1fr))", gap: 22, margin: "2px 0 18px" }}>
          <Stat value={baseline ? pct(baseline.acc_pct) : "—"} label="Baseline accuracy" color={ARM.baseline} sub="markdown + SQL" />
          <Stat value={best ? pct(best.acc_pct) : "—"} label="Best Malloy accuracy" color={ARM.malloy} sub="never reaches baseline" />
          <Stat value={tokMult ? `${tokMult.toFixed(1)}×` : "—"} label="Prompt tokens, same model" color={PATH.sql} sub="the substrate tax" />
        </div>
        <Figure caption={<>Each Malloy run against the baseline (dashed) — <b>none reach it</b>. At a fixed model, the substrate alone costs {tokMult ? `${tokMult.toFixed(1)}×` : ""} the prompt tokens. <Link onClick={go("metrics")}>the full matrix</Link></>}>
          {runsQ.isLoading ? <div className="animate-pulse" style={{ height: 210, background: "#eceae3", borderRadius: 3 }} /> : (
            <>
              <ResponsiveContainer width="100%" height={210}>
                <BarChart data={chart} layout="vertical" margin={{ left: 8, right: 52, top: 14, bottom: 4 }}>
                  <XAxis type="number" domain={[0, 100]} hide />
                  <YAxis type="category" dataKey="label" width={188} tick={{ fontSize: 11, fill: INK.muted, fontFamily: SANS }} axisLine={false} tickLine={false} />
                  {baseline ? <ReferenceLine x={N(baseline.acc_pct)} stroke={ARM.baseline} strokeDasharray="4 3" label={{ value: `baseline ${pct(baseline.acc_pct)}`, position: "top", fontSize: 10.5, fill: ARM.baseline, fontFamily: SANS }} /> : null}
                  <Bar dataKey="acc" fill={ARM.malloy} radius={[0, 2, 2, 0]} barSize={14} isAnimationActive={false}>
                    <LabelList dataKey="acc" position="right" formatter={(v: number) => `${v}%`} style={{ fontFamily: MONO, fontSize: 11, fill: INK.text }} />
                  </Bar>
                </BarChart>
              </ResponsiveContainer>
              <div style={{ fontFamily: SANS, fontSize: 11, color: INK.faint, marginTop: 4, lineHeight: 1.6 }}>
                {RUN_KEY.map(([t, d], i) => <span key={t} style={{ marginRight: 12 }}><b style={{ color: INK.muted }}>{t}</b> {d}</span>)}
              </div>
            </>
          )}
        </Figure>
      </Chapter>

      <Chapter n={4} title="Three findings">
        <ol style={{ paddingLeft: 0, listStyle: "none", display: "flex", flexDirection: "column", gap: 15, margin: 0 }}>
          <li>
            <b style={{ fontFamily: SANS, fontSize: 13 }}>1 · The token tax is structural.</b>
            <p style={{ margin: "3px 0 0" }}>More layer, more per-query Malloy, a view catalog to read — <b>{tokMult ? `${tokMult.toFixed(1)}×` : "~2.5×"}</b> the
              prompt tokens at a fixed model, no accuracy gained. <Link onClick={go("metrics")}>compare runs</Link></p>
          </li>
          <li>
            <b style={{ fontFamily: SANS, fontSize: 13 }}>2 · The layer is mostly bypassed.</b>
            <p style={{ margin: "3px 0 0" }}>The best run answered <b style={{ color: PATH.sql }}>{officialSql.toFixed(0)}% of questions in raw SQL</b>, not
              Malloy, and touched only <b>12 of 83</b> views. Fixing the layer’s defect changed nothing — it wasn’t doing the work. <Link onClick={go("layer")}>view utilization</Link></p>
          </li>
          <li>
            <b style={{ fontFamily: SANS, fontSize: 13 }}>3 · A compiled view freezes one interpretation; prose adapts.</b>
            <p style={{ margin: "3px 0 0" }}>When a question fits a pre-built view, Malloy matches the baseline. When it doesn’t, the view applies
              <b> one frozen interpretation</b> — and the wrong logic persists even after the agent bails to SQL. Documented patterns can be
              re-read and adapted per question; a compiled view can’t. <span style={{ color: INK.muted }}>(Example — a fee-ranking question the layer
              answered by <i>averaging</i> where the answer is a <i>sum</i>: baseline
              {aBase ? <b style={{ color: ARM.baseline }}> {N(aBase.correct)}/{N(aBase.n)}</b> : " —"}, the view
              {aView ? <b style={{ color: PATH.sql }}> {N(aView.correct)}/{N(aView.n)}</b> : " —"}, the SQL bail
              {aSql ? <b> {N(aSql.correct)}/{N(aSql.n)}</b> : " —"}.)</span>{" "}
              <Link onClick={go("metrics", () => setAci("1443"))}>see it</Link> · <Link onClick={go("traces", () => { setTraceRun(PREFIX); setTraceTask("1443"); })}>trace it</Link></p>
          </li>
        </ol>
      </Chapter>

      <Chapter n={5} title="The verdict">
        <p>Used as the agent’s primary answering substrate, Malloy was slower, heavier, and less accurate than
          context + SQL. When the path was obvious it could match the baseline — at a token and latency premium.
          When it wasn’t, the executable view froze the wrong interpretation while prose just adapted.</p>
        <p style={{ marginTop: 10 }}>Here’s the part I didn’t expect: <b>models write passable Malloy</b> — it compiles, runs, and
          generalizes. Models readily synthesize SQL but struggle to make Malloy <i>dance</i>; the dominant failure here isn’t
          authoring, it’s using the layer as the thinking medium. <Link onClick={go("build")}>how the layer was built</Link></p>
        <div style={{ marginTop: 12, padding: "10px 14px", borderLeft: `3px solid ${INK.faint}`, background: INK.panel }}>
          <span style={{ fontFamily: SANS, fontSize: 12.5, color: INK.text }}>
            <b>Scope.</b> One benchmark, one harness, one layer build — this is about Malloy <i>as an LLM substrate</i>. It
            says nothing about a semantic layer as a deterministic interface for non-agent systems, which I didn’t test.</span>
        </div>
      </Chapter>

      <Chapter n={6} title="What I’d build next">
        <p>The layer’s value isn’t helping the model reason — it’s making chosen definitions <b>executable,
          governed, testable, and reusable outside the LLM loop</b>: provenance, permissions, lineage, metric
          contracts, regression tests, interoperability with non-agent tools. The shape:</p>
        <ul style={{ paddingLeft: 18, margin: "8px 0", display: "flex", flexDirection: "column", gap: 5 }}>
          <li><b>Context is the authoring and reasoning substrate</b>; SQL is the execution language.</li>
          <li><b>Semantic-layer objects are promoted artifacts</b>, not the default medium — promotion requires tests, so a bad interpretation can’t freeze.</li>
          <li><b>Force a governed lookup first, with clear off-ramps</b> — if it doesn’t fit, use the layer as <i>context</i> for a SQL answer, and log a promotion candidate. <span style={{ color: INK.muted }}>(My stance; force-first vs. optional is still open.)</span></li>
        </ul>
        <Figure caption={<>The strongest proxy — the {best ? pct(best.acc_pct) : ""} hybrid. Governed lookup (<b style={{ color: APATH.view }}>view-selection</b>) carried only {pN("view")} of {pTot}; the agent <b style={{ color: APATH.sql }}>off-ramped to SQL</b> for {pN("sql")}. The off-ramp helped — the lookup couldn’t carry most questions. <b>Enough to validate the direction, not the protocol.</b></>}>
          {pathQ.isLoading ? <div className="animate-pulse" style={{ height: 38, background: "#eceae3", borderRadius: 3 }} /> : (
            <div>
              <div style={{ display: "flex", height: 30, borderRadius: 3, overflow: "hidden", border: `1px solid ${INK.rule}` }}>
                {(["view", "authored", "sql", "other"] as const).map((k) => {
                  const n = pN(k); if (!n) return null;
                  return <div key={k} title={`${k}: ${n}`} style={{ width: `${(n / pTot) * 100}%`, background: APATH[k], display: "flex", alignItems: "center", justifyContent: "center" }}>
                    <span style={{ fontFamily: MONO, fontSize: 11, color: k === "authored" ? INK.text : "#fff" }}>{n}</span></div>;
                })}
              </div>
              <div style={{ display: "flex", gap: 14, marginTop: 6, fontFamily: SANS, fontSize: 11.5, color: INK.muted }}>
                <span><span style={{ color: APATH.view }}>■</span> view-selection</span>
                <span><span style={{ color: APATH.authored }}>■</span> authored Malloy</span>
                <span><span style={{ color: APATH.sql }}>■</span> SQL off-ramp</span>
              </div>
            </div>
          )}
        </Figure>
        <p style={{ fontSize: 13.5, color: INK.muted, fontStyle: "italic" }}>The next test isn’t a benchmark — a repeated,
          multi-consumer workload with a hard protocol (lookup → judge fit → off-ramp → promote), where governance and the promotion flywheel are observable.</p>
      </Chapter>
    </div>
  );
}


// ───────── MetricsTab.tsx ─────────

const pathColor = (p: string) => (p === "sql" ? PATH.sql : p === "view" ? "#0a6aa8" : p === "authored" ? "#7ba6c4" : PATH.other);

function MetricsTab() {
  const matrix = useSQLQuery(`SELECT run_label, arm, n, correct, acc_pct, hard_acc, easy_acc, pct_sql, pct_malloy,
      round(median_prompt_tokens) AS tok, round(cost_usd,2) AS cost, escalations
    FROM "agentic_malloy_story"."main"."runs" WHERE split='test' ORDER BY arm DESC, acc_pct DESC`);
  const overfit = useSQLQuery(`SELECT tier, split, round(avg(acc_pct),1) AS avg_acc, count(*) AS runs
    FROM "agentic_malloy_story"."main"."runs" WHERE arm='malloy' AND layer_label='committed' AND tier IN ('sonnet+opus','gemini')
    GROUP BY tier, split ORDER BY tier, split DESC`);

  const m = rows(matrix.data);

  // ── ACI three-story side-by-side ──
  const [task, setTask] = useDiveState<string>("aci_task", "1443");
  const aciTasks = useSQLQuery(`SELECT task_id FROM "agentic_malloy_story"."main"."tasks" WHERE family='aci_most_expensive_template' ORDER BY TRY_CAST(task_id AS INT)`);
  const story3 = useSQLQuery(`SELECT run_label, arm, answer_path, is_correct, predicted, gold,
      coalesce(malloy_source, compiled_sql) AS code
    FROM "agentic_malloy_story"."main"."results"
    WHERE task_id='${esc(task)}' AND run_label IN
      ('Baseline · markdown+SQL (gemini)','Malloy · sonnet+opus · official (pre-fix)','Malloy · sonnet+opus · official')
    ORDER BY CASE WHEN arm='baseline' THEN 0 WHEN run_label LIKE '%pre-fix%' THEN 1 ELSE 2 END`);
  const cards = rows(story3.data);
  const cardTitle = (r: any) => r.arm === "baseline" ? "Baseline — SUM (markdown+SQL)"
    : String(r.run_label).includes("pre-fix") ? "Malloy — the AVG layer view" : "Malloy — bailed to SQL";

  // ── results explorer ──
  const PAGE = 20;
  const [run, setRun] = useDiveState<string>("ex_run", "Malloy · sonnet+opus · official");
  const [level, setLevel] = useDiveState<string>("ex_level", "all");
  const [path, setPath] = useDiveState<string>("ex_path", "all");
  const [correct, setCorrect] = useDiveState<string>("ex_correct", "all");
  const [onlyAF, setOnlyAF] = useDiveState<string>("ex_af", "no");
  const [page, setPage] = useDiveState<number>("ex_page", 0);
  const runOpts = m.map((r) => String(r.run_label));
  const w: string[] = [`r.run_label='${esc(run)}'`];
  if (level !== "all") w.push(`r.level='${esc(level)}'`);
  if (path !== "all") w.push(`r.answer_path='${esc(path)}'`);
  if (correct !== "all") w.push(`r.is_correct=${correct === "correct"}`);
  if (onlyAF === "yes") w.push(`t.always_fail`);
  const where = w.join(" AND ");
  const countQ = useSQLQuery(`SELECT count(*) AS n FROM "agentic_malloy_story"."main"."results" r JOIN "agentic_malloy_story"."main"."tasks" t USING (task_id) WHERE ${where}`);
  const total = N(rows(countQ.data)[0]?.n);
  const pages = Math.max(1, Math.ceil(total / PAGE));
  const cur = Math.min(Math.max(0, page), pages - 1);
  const explorer = useSQLQuery(`SELECT r.task_id, r.level, t.family, r.answer_path, r.is_correct, r.predicted, t.gold_result AS gold
    FROM "agentic_malloy_story"."main"."results" r JOIN "agentic_malloy_story"."main"."tasks" t USING (task_id)
    WHERE ${where} ORDER BY r.is_correct, TRY_CAST(r.task_id AS INT) LIMIT ${PAGE} OFFSET ${cur * PAGE}`);
  const ex = rows(explorer.data);
  const pBtn = (off: boolean): React.CSSProperties => ({ fontFamily: SANS, fontSize: 11, padding: "2px 9px", borderRadius: 4, border: `1px solid ${INK.rule}`, background: INK.paper, color: off ? INK.faint : ARM.malloy, cursor: off ? "default" : "pointer" });
  const setFilter = (fn: (v: string) => void) => (v: string) => { fn(v); setPage(0); };

  const of = rows(overfit.data);
  const ofRow = (tier: string, split: string) => of.find((r) => r.tier === tier && r.split === split);

  return (
    <div>
      {/* ── matrix ── */}
      <Head kicker="every number queried live" title="The run matrix">All six Malloy configurations and the baseline, on the same 419-task held-out set and DABstep scorer.</Head>
      <Figure caption={<>Accuracy and the share of answers the agent submitted as <b style={{ color: PATH.sql }}>raw SQL</b> rather than Malloy. The “best” Malloy run leans on SQL for the majority of answers.</>}>
        {matrix.isLoading ? <Loading label="loading runs…" /> : (
          <div style={{ overflowX: "auto" }}>
            <table style={{ borderCollapse: "collapse", width: "100%", minWidth: 640 }}>
              <thead><tr>
                <th style={thL}>Substrate / run</th><th style={th}>Accuracy</th><th style={th}>Hard</th><th style={th}>Easy</th>
                <th style={th}>% via SQL</th><th style={th}>Med tok</th><th style={th}>Cost</th>
              </tr></thead>
              <tbody>
                {m.map((r) => {
                  const base = r.arm === "baseline";
                  return (
                    <tr key={String(r.run_label)} style={{ background: base ? "#eef3e8" : "transparent" }}>
                      <td style={{ ...tdL, fontWeight: base ? 700 : 400, color: base ? ARM.baseline : INK.text }}><Tip text={noteFor(String(r.run_label))}>{String(r.run_label)}</Tip></td>
                      <td style={td}><BarCell value={N(r.acc_pct)} color={base ? ARM.baseline : ARM.malloy} label={pct(r.acc_pct)} /></td>
                      <td style={td}>{pct(r.hard_acc)}</td>
                      <td style={td}>{N(r.easy_acc) ? pct(r.easy_acc) : "—"}</td>
                      <td style={td}><BarCell value={N(r.pct_sql)} color={PATH.sql} label={base ? "—" : `${N(r.pct_sql).toFixed(0)}%`} /></td>
                      <td style={td}>{N(r.tok).toLocaleString()}</td>
                      <td style={td}>${N(r.cost)}</td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </Figure>

      <Rule />

      {/* ── ACI three-story ── */}
      <Head kicker="the template that always failed" title="A fee-ranking question, three ways to be wrong">
        “Which routing code costs the most for a transaction?” The layer ranks by the AVERAGE rule fee; the right answer SUMs the fees a transaction actually incurs — so the view is wrong regardless of model. The same task, three ways:
      </Head>
      <div style={{ marginBottom: 12, fontFamily: SANS }}>
        <span style={{ fontSize: 12, color: INK.muted, marginRight: 8 }}>task</span>
        <select value={task} onChange={(e) => setTask(e.target.value)} style={{ ...sel, fontFamily: MONO }}>
          {rows(aciTasks.data).map((t) => <option key={String(t.task_id)} value={String(t.task_id)}>{String(t.task_id)}</option>)}
        </select>
      </div>
      {story3.isLoading ? <Loading label="loading…" /> : (
        <div style={{ display: "flex", gap: 12, flexWrap: "wrap" }}>
          {cards.map((r) => {
            const good = r.is_correct;
            return (
              <div key={String(r.run_label)} style={{ flex: "1 1 260px", border: `1px solid ${INK.rule}`, borderTop: `3px solid ${pathColor(String(r.answer_path))}`, background: INK.paper }}>
                <div style={{ padding: "8px 11px" }}>
                  <div style={{ fontFamily: SANS, fontWeight: 700, fontSize: 12.5, color: INK.text }}>{cardTitle(r)}</div>
                  <div style={{ fontFamily: SANS, fontSize: 11, color: INK.muted, marginTop: 2 }}>
                    submitted as <b style={{ color: pathColor(String(r.answer_path)) }}>{String(r.answer_path)}</b> ·
                    predicted <b style={{ fontFamily: MONO }}>{String(r.predicted)}</b> vs gold <b style={{ fontFamily: MONO }}>{String(r.gold)}</b>{" "}
                    <span style={{ color: good ? ARM.baseline : PATH.sql, fontWeight: 700 }}>{good ? "✓" : "✗"}</span>
                  </div>
                </div>
                <pre style={{ margin: 0, padding: 11, fontFamily: MONO, fontSize: 10, color: INK.text, background: INK.panel, borderTop: `1px solid ${INK.rule}`, overflowX: "auto", maxHeight: 200, whiteSpace: "pre-wrap" }}>
                  {String(r.code ?? "(none)").slice(0, 1100)}
                </pre>
              </div>
            );
          })}
        </div>
      )}
      <p style={{ fontFamily: SERIF, fontStyle: "italic", fontSize: 12.5, color: INK.muted, marginTop: 8 }}>
        The pre-fix run used the layer’s AVG view and was wrong; the official run abandoned the layer for SQL — and on many ACI tasks transcribed the same wrong recipe. The defect is the computational model the layer instills, not the language.
      </p>

      <Rule />

      {/* ── results explorer ── */}
      <Head kicker="interrogate it yourself" title="Per-question results explorer">Filter any run’s 419 answers by level, answer path, and correctness.</Head>
      <div style={{ display: "flex", gap: 14, flexWrap: "wrap", marginBottom: 12, fontFamily: SANS, fontSize: 12, alignItems: "center" }}>
        <label>run <select value={run} onChange={(e) => setFilter(setRun)(e.target.value)} style={sel}>{runOpts.map((o) => <option key={o} value={o}>{o}</option>)}</select></label>
        <label>level <select value={level} onChange={(e) => setFilter(setLevel)(e.target.value)} style={sel}><option value="all">all</option><option value="hard">hard</option><option value="easy">easy</option></select></label>
        <label>path <select value={path} onChange={(e) => setFilter(setPath)(e.target.value)} style={sel}><option value="all">all</option><option value="view">view-selection</option><option value="authored">authored</option><option value="sql">sql</option><option value="other">other</option></select></label>
        <label>result <select value={correct} onChange={(e) => setFilter(setCorrect)(e.target.value)} style={sel}><option value="all">all</option><option value="correct">correct</option><option value="incorrect">incorrect</option></select></label>
        <label><input type="checkbox" checked={onlyAF === "yes"} onChange={(e) => { setOnlyAF(e.target.checked ? "yes" : "no"); setPage(0); }} /> always-fail only</label>
      </div>
      {explorer.isLoading ? <Loading label="loading results…" /> : (
        <div style={{ overflowX: "auto" }}>
          <div style={{ display: "flex", alignItems: "center", gap: 10, fontFamily: SANS, fontSize: 11, color: INK.muted, marginBottom: 4 }}>
            <span>{total} rows</span>
            <button disabled={cur <= 0} onClick={() => setPage(cur - 1)} style={pBtn(cur <= 0)}>‹ prev</button>
            <span>page {cur + 1} of {pages}</span>
            <button disabled={cur >= pages - 1} onClick={() => setPage(cur + 1)} style={pBtn(cur >= pages - 1)}>next ›</button>
          </div>
          <table style={{ borderCollapse: "collapse", width: "100%", minWidth: 560 }}>
            <thead><tr><th style={thL}>task</th><th style={thL}>level</th><th style={thL}>family</th><th style={thL}>path</th><th style={th}>✓</th><th style={thL}>predicted</th><th style={thL}>gold</th></tr></thead>
            <tbody>
              {ex.map((r, i) => (
                <tr key={i}>
                  <td style={{ ...tdL, fontFamily: MONO }}>{String(r.task_id)}</td>
                  <td style={tdL}>{String(r.level)}</td>
                  <td style={{ ...tdL, fontSize: 11, color: INK.muted }}>{r.family ? "ACI template" : "—"}</td>
                  <td style={{ ...tdL, color: pathColor(String(r.answer_path)), fontWeight: 600 }}>{String(r.answer_path)}</td>
                  <td style={{ ...td, color: r.is_correct ? ARM.baseline : PATH.sql, fontWeight: 700 }}>{r.is_correct ? "✓" : "✗"}</td>
                  <td style={{ ...tdL, fontFamily: MONO, fontSize: 11, maxWidth: 160, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{String(r.predicted ?? "")}</td>
                  <td style={{ ...tdL, fontFamily: MONO, fontSize: 11, maxWidth: 160, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{String(r.gold ?? "")}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      <Rule />

      {/* ── overfit ── */}
      <Head kicker="is the layer overfit to train?" title="Train vs held-out">The layer was authored by reading the 26 train Q/A, so held-out is the honest test. It tracks train — the layer generalizes; it is simply less efficient.</Head>
      {overfit.isLoading ? <Loading label="loading…" /> : (
        <div style={{ display: "flex", gap: 30, fontFamily: SANS, flexWrap: "wrap" }}>
          {(["sonnet+opus", "gemini"] as const).map((tier) => {
            const tr = ofRow(tier, "train"); const te = ofRow(tier, "test");
            return (
              <div key={tier}>
                <div style={{ fontSize: 12, color: INK.muted, marginBottom: 4 }}>{tier} · committed layer</div>
                <div style={{ display: "flex", gap: 18 }}>
                  <div><div style={{ fontFamily: MONO, fontSize: 22, color: INK.text }}>{tr ? pct(tr.avg_acc) : "—"}</div><div style={{ fontSize: 11, color: INK.faint }}>train (avg, {tr ? N(tr.runs) : 0} runs)</div></div>
                  <div style={{ alignSelf: "center", color: INK.faint }}>→</div>
                  <div><div style={{ fontFamily: MONO, fontSize: 22, color: ARM.malloy }}>{te ? pct(te.avg_acc) : "—"}</div><div style={{ fontSize: 11, color: INK.faint }}>held-out</div></div>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}


// ───────── BuildTab.tsx ─────────

function BuildTab() {
  const surf = useSQLQuery(`SELECT
      (SELECT length(content) FROM "agentic_malloy_story"."main"."documents" WHERE kind='skill') AS malloy_skill,
      (SELECT coalesce(length(content),0) FROM "agentic_malloy_story"."main"."documents" WHERE kind='primer') AS malloy_primer,
      (SELECT coalesce(length(content),0) FROM "agentic_malloy_story"."main"."documents" WHERE kind='glossary') AS malloy_glossary,
      (SELECT coalesce(sum(length(content)),0) FROM "agentic_malloy_story"."main"."documents" WHERE kind='layer') AS malloy_layer,
      (SELECT count(*) FROM "agentic_malloy_story"."main"."documents" WHERE kind='layer') AS malloy_layer_n,
      (SELECT coalesce(sum(length(content)),0) FROM "agentic_malloy_story"."main"."documents" WHERE kind='layer_meta') AS malloy_meta,
      (SELECT count(*) FROM "agentic_malloy_story"."main"."documents" WHERE kind='layer_meta') AS malloy_meta_n,
      (SELECT length(content) FROM "agentic_malloy_story"."main"."documents" WHERE kind='baseline_skill') AS base_skill,
      (SELECT count(*) FROM "agentic_malloy_story"."main"."documents" WHERE kind='baseline_context') AS base_ctx_n,
      (SELECT sum(length(content)) FROM "agentic_malloy_story"."main"."documents" WHERE kind='baseline_context') AS base_ctx_chars`);
  const ctxList = useSQLQuery(`SELECT title, length(content) AS chars FROM "agentic_malloy_story"."main"."documents" WHERE kind='baseline_context' ORDER BY title`);
  const layerList = useSQLQuery(`SELECT title, length(content) AS chars FROM "agentic_malloy_story"."main"."documents" WHERE kind='layer' ORDER BY title`);
  const metaList = useSQLQuery(`SELECT title, length(content) AS chars FROM "agentic_malloy_story"."main"."documents" WHERE kind='layer_meta' ORDER BY title`);

  const [doc, setDoc] = useDiveState<string>("build_doc", "malloy_skill");
  const docQ = useSQLQuery(
    doc === "malloy_skill" ? `SELECT content FROM "agentic_malloy_story"."main"."documents" WHERE kind='skill' LIMIT 1`
    : doc === "primer" ? `SELECT content FROM "agentic_malloy_story"."main"."documents" WHERE kind='primer' LIMIT 1`
    : doc === "glossary" ? `SELECT content FROM "agentic_malloy_story"."main"."documents" WHERE kind='glossary' LIMIT 1`
    : doc === "baseline_skill" ? `SELECT content FROM "agentic_malloy_story"."main"."documents" WHERE kind='baseline_skill' LIMIT 1`
    : doc.startsWith("layer::") ? `SELECT content FROM "agentic_malloy_story"."main"."documents" WHERE kind='layer' AND title='${doc.slice(7).replace(/'/g, "''")}' LIMIT 1`
    : doc.startsWith("meta::") ? `SELECT content FROM "agentic_malloy_story"."main"."documents" WHERE kind='layer_meta' AND title='${doc.slice(6).replace(/'/g, "''")}' LIMIT 1`
    : `SELECT content FROM "agentic_malloy_story"."main"."documents" WHERE kind='baseline_context' AND title='${doc.replace(/'/g, "''")}' LIMIT 1`,
  );

  const provQ = useSQLQuery(`SELECT content FROM "agentic_malloy_story"."main"."documents" WHERE kind='provenance' LIMIT 1`);
  const layerFiles = useSQLQuery(`SELECT count(*) AS n, sum(length(content)) AS chars FROM "agentic_malloy_story"."main"."documents" WHERE kind='layer'`);
  let prov: any = {};
  try { prov = JSON.parse(String(rows(provQ.data)[0]?.content ?? "{}")); } catch { prov = {}; }
  const lf = rows(layerFiles.data)[0] || {};

  const s = rows(surf.data)[0] || {};
  // Fair comparison by WORKFLOW: each arm = what it INJECTS into every prompt +
  // the deeper surface it RETRIEVES on demand. Itemized to every curated artifact.
  //   Malloy injected: skill.md + Malloy primer + glossary (cli.ts system prompt)
  //   Malloy retrieved: .malloy models + _meta sidecars (list_views / get_file)
  //   Baseline injected: SKILL.md ; retrieved: context items (semantic_lookup)
  const mSkill = N(s.malloy_skill), mPrimer = N(s.malloy_primer), mGloss = N(s.malloy_glossary);
  const mLayer = N(s.malloy_layer), mMeta = N(s.malloy_meta);
  const malloyTotal = mSkill + mPrimer + mGloss + mLayer + mMeta;
  const bSkill = N(s.base_skill), bCtx = N(s.base_ctx_chars);
  const baseTotal = bSkill + bCtx;
  const maxTotal = Math.max(malloyTotal, baseTotal) || 1;
  const mult = baseTotal ? malloyTotal / baseTotal : 0;   // Malloy surface vs baseline surface
  // Malloy blues (injected → darker, retrieved → lighter); baseline greens.
  const surfaceBars = [
    { arm: "Malloy arm", labelColor: ARM.malloy, total: malloyTotal,
      files: 1 + 1 + 1 + N(s.malloy_layer_n) + N(s.malloy_meta_n),
      segs: [
        { label: "skill.md", chars: mSkill, role: "injected", color: "#0a6aa8" },
        { label: "Malloy primer", chars: mPrimer, role: "injected", color: "#2f86c2" },
        { label: "domain glossary (YAML)", chars: mGloss, role: "injected", color: "#5aa0d0" },
        { label: `${N(s.malloy_layer_n)} .malloy models`, chars: mLayer, role: "retrieved", color: "#a9cce6" },
        { label: `${N(s.malloy_meta_n)} _meta sidecars (YAML)`, chars: mMeta, role: "retrieved", color: "#cfe3f2" },
      ] },
    { arm: "Baseline", labelColor: ARM.baseline, total: baseTotal, files: 1 + N(s.base_ctx_n),
      segs: [
        { label: "SKILL.md", chars: bSkill, role: "injected", color: "#2d6a2d" },
        { label: `${N(s.base_ctx_n)} context items`, chars: bCtx, role: "retrieved", color: "#9cc49c" },
      ] },
  ];
  const flow = ["explore (MCP SQL)", "list_views / get_file", "author Malloy", "run_malloy → compile → exec", "submit (Malloy or SQL)"];
  const buildFlow = ["read manual + 26 train Q/A + schema", "author the layer (source-per-entity → joins → views)", "compile + execute every view (P0 gate)", "repair loop on failures", "hash + lock provenance"];

  return (
    <div>
      <Head kicker="this is not a “bad Malloy” story" title="The layer was authored by a model, not a human">
        A procedure builds it: an expensive model reads the manual, the 26 train Q/A, and the schema, then writes the
        whole layer — compile-and-execute-gated, with a repair loop, then provenance-locked. I only tune the build
        prompt; I never hand-edit the layer files. The result is functional Malloy that generalizes — the problem is using it.
      </Head>
      <div style={{ display: "flex", flexWrap: "wrap", gap: 7, alignItems: "center", marginBottom: 12 }}>
        {buildFlow.map((s2, i) => (
          <div key={s2} style={{ display: "flex", alignItems: "center", gap: 7 }}>
            <span style={{ fontFamily: SANS, fontSize: 11.5, padding: "4px 9px", border: `1px solid ${INK.rule}`, borderRadius: 4, background: INK.paper, color: INK.text }}>{s2}</span>
            {i < buildFlow.length - 1 ? <span style={{ color: INK.faint }}>→</span> : null}
          </div>
        ))}
      </div>
      <div style={{ display: "flex", gap: 26, flexWrap: "wrap", fontFamily: SANS, fontSize: 12, marginBottom: 6 }}>
        {[["provenance", String(prov.malloy_provenance ?? "—")],
          ["authoring model", String(prov.authoring_model ?? "—").replace("anthropic/", "")],
          ["manual included", prov.manual_included ? "yes" : "no"],
          ["improve rounds", String(prov.improve_round ?? 0)],
          ["model hash", String(prov.malloy_model_hash ?? "—")],
          ["layer size", `${N(lf.n)} files · ${N(lf.chars).toLocaleString()} ch`]].map(([k, v]) => (
          <div key={k as string}><div style={{ color: INK.faint, fontSize: 11 }}>{k as string}</div><div style={{ fontFamily: MONO, color: INK.text }}>{v as string}</div></div>
        ))}
      </div>
      <p style={{ fontFamily: SERIF, fontStyle: "italic", fontSize: 12.5, color: INK.muted }}>
        An <b>official</b> run fails fast unless the on-disk layer still hashes to the recorded value — a hand-edit
        breaks the hash and disqualifies the run. So the 91.2% is genuinely model-authored Malloy.
      </p>

      <Rule />

      <Head kicker="how the agent was set up" title="The harness">A two-model author→fixer loop explores via MotherDuck MCP, authors Malloy, compiles it to SQL (a deterministic translation-check), and submits. On repeated compile errors it steers in place rather than escalating to the bigger model.</Head>
      <div style={{ display: "flex", flexWrap: "wrap", gap: 7, alignItems: "center", marginBottom: 8 }}>
        {flow.map((s2, i) => (
          <div key={s2} style={{ display: "flex", alignItems: "center", gap: 7 }}>
            <span style={{ fontFamily: SANS, fontSize: 11.5, padding: "4px 9px", border: `1px solid ${INK.rule}`, borderRadius: 4, background: INK.paper, color: INK.text }}>{s2}</span>
            {i < flow.length - 1 ? <span style={{ color: INK.faint }}>→</span> : null}
          </div>
        ))}
      </div>
      <p style={{ fontFamily: SERIF, fontStyle: "italic", fontSize: 12.5, color: INK.muted }}>The Malloy answer compiles to SQL, so the Malloy→SQL translation is checkable; the layer is model-authored (provenance-gated, never hand-edited).</p>

      <Rule />

      <Head kicker="is the comparison fair?" title="The tuning asymmetry">Neither arm is “just” its answer-time skill. Each one <b>injects</b> a skill into every prompt and <b>browses</b> a deeper surface on demand. Itemized fairly — every curated artifact each arm carries — the Malloy arm is {mult ? `${mult.toFixed(1)}×` : ""} the baseline’s surface. So the gap isn’t “less context to work with.”</Head>
      <Figure caption={<>Every curated artifact in each arm’s surface, in characters. <b>Injected</b> into every prompt (left of the divider): the baseline’s SKILL.md; the Malloy arm’s skill.md + Malloy primer + domain glossary. <b>Browsed on demand</b> (right): the baseline’s {N(s.base_ctx_n)} context items via <i>semantic_lookup</i>; the Malloy arm’s {N(s.malloy_layer_n)} .malloy models + {N(s.malloy_meta_n)} _meta sidecars via <i>list_views</i>/<i>get_file</i> — the navigation path into the models. The Malloy arm is {mult ? `${mult.toFixed(1)}×` : ""} the baseline’s surface; the easy-question gap isn’t a resourcing gap. (These are authored-artifact sizes — only part of each enters a given prompt: e.g. the {N(s.malloy_glossary).toLocaleString()}-ch glossary renders to ~8.6K. Under-use is the next section’s point.)</>}>
        {surf.isLoading ? <Loading label="measuring…" /> : (
          <div style={{ display: "flex", flexDirection: "column", gap: 16, maxWidth: 620 }}>
            {surfaceBars.map((b) => (
              <div key={b.arm}>
                <div style={{ display: "flex", justifyContent: "space-between", fontFamily: SANS, fontSize: 12, marginBottom: 4 }}>
                  <span style={{ color: b.labelColor, fontWeight: 600 }}>{b.arm}</span>
                  <span style={{ fontFamily: MONO, color: INK.muted }}>{N(b.total).toLocaleString()} ch · {b.files} files</span>
                </div>
                <div style={{ display: "flex", height: 20, width: `${(b.total / maxTotal) * 100}%`, minWidth: 3, borderRadius: 2, overflow: "hidden", border: `1px solid ${INK.rule}` }}>
                  {b.segs.map((seg, i) => {
                    const boundary = i > 0 && seg.role === "retrieved" && b.segs[i - 1].role === "injected";
                    return (
                      <div key={seg.label} title={`${seg.label} — ${N(seg.chars).toLocaleString()} ch · ${seg.role}`}
                        style={{ width: `${b.total ? (seg.chars / b.total) * 100 : 0}%`, background: seg.color,
                          boxShadow: "inset -1px 0 0 rgba(255,255,255,0.7)", borderLeft: boundary ? `2px solid ${INK.text}` : "none" }} />
                    );
                  })}
                </div>
                <div style={{ display: "flex", gap: 20, marginTop: 6, flexWrap: "wrap" }}>
                  {(["injected", "retrieved"] as const).map((role) => {
                    const segs = b.segs.filter((x) => x.role === role);
                    if (!segs.length) return null;
                    return (
                      <div key={role} style={{ display: "flex", flexDirection: "column", gap: 3 }}>
                        <span style={{ fontFamily: SANS, fontSize: 9.5, letterSpacing: "0.06em", textTransform: "uppercase", color: INK.faint }}>
                          {role === "injected" ? "injected every prompt" : "browsed on demand"}
                        </span>
                        <div style={{ display: "flex", gap: 10, flexWrap: "wrap" }}>
                          {segs.map((seg) => (
                            <span key={seg.label} style={{ display: "inline-flex", alignItems: "center", gap: 4, fontFamily: SANS, fontSize: 10.5, color: INK.muted }}>
                              <span style={{ width: 9, height: 9, borderRadius: 1, background: seg.color, border: `1px solid ${INK.rule}` }} />
                              {seg.label} <span style={{ fontFamily: MONO, color: INK.faint }}>{N(seg.chars).toLocaleString()}</span>
                            </span>
                          ))}
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>
            ))}
          </div>
        )}
      </Figure>

      <Head title="Read the prompts">&nbsp;</Head>
      <div style={{ marginBottom: 10, fontFamily: SANS, fontSize: 12 }}>
        <select value={doc} onChange={(e) => setDoc(e.target.value)} style={sel}>
          <optgroup label="Malloy — injected every prompt">
            <option value="malloy_skill">skill.md ({N(mSkill)} ch)</option>
            <option value="primer">malloy-primer.md ({N(mPrimer)} ch)</option>
            <option value="glossary">_glossary.yaml ({N(mGloss)} ch)</option>
          </optgroup>
          <optgroup label="Malloy — semantic layer, .malloy models (browsed)">
            {rows(layerList.data).map((c) => <option key={`layer::${c.title}`} value={`layer::${c.title}`}>{String(c.title)} ({N(c.chars)} ch)</option>)}
          </optgroup>
          <optgroup label="Malloy — _meta navigation sidecars, YAML (browsed)">
            {rows(metaList.data).map((c) => <option key={`meta::${c.title}`} value={`meta::${c.title}`}>{String(c.title)} ({N(c.chars)} ch)</option>)}
          </optgroup>
          <optgroup label="Baseline — injected every prompt">
            <option value="baseline_skill">SKILL.md ({N(bSkill)} ch)</option>
          </optgroup>
          <optgroup label="Baseline — context items (browsed)">
            {rows(ctxList.data).map((c) => <option key={String(c.title)} value={String(c.title)}>{String(c.title)} ({N(c.chars)} ch)</option>)}
          </optgroup>
        </select>
      </div>
      {docQ.isLoading ? <Loading label="loading…" /> : (
        <pre style={{ margin: 0, padding: 13, fontFamily: MONO, fontSize: 11, color: INK.text, background: INK.paper, border: `1px solid ${INK.rule}`, borderRadius: 4, overflow: "auto", maxHeight: 440, whiteSpace: "pre-wrap" }}>
          {String(rows(docQ.data)[0]?.content ?? "")}
        </pre>
      )}
    </div>
  );
}


// ───────── LayerTab.tsx ─────────

function LayerTab() {
  const vu = useSQLQuery(`SELECT view_name, file, referenced, used FROM "agentic_malloy_story"."main"."view_utilization" ORDER BY referenced DESC`);
  const rvu = useSQLQuery(`SELECT run_label, views_used FROM "agentic_malloy_story"."main"."run_view_usage" ORDER BY views_used DESC`);
  const files = useSQLQuery(`SELECT title, length(content) AS chars FROM "agentic_malloy_story"."main"."documents" WHERE kind='layer' ORDER BY chars DESC`);
  const rebuild = useSQLQuery(`SELECT layer_label, round(avg(acc_pct),1) AS avg_acc, min(correct) AS mn, max(correct) AS mx, round(avg(n)) AS n
    FROM "agentic_malloy_story"."main"."runs" WHERE arm='malloy' AND split='train' AND tier='sonnet+opus' GROUP BY layer_label`);

  const [file, setFile] = useDiveState<string>("layer_file", "");
  const body = useSQLQuery(`SELECT content FROM "agentic_malloy_story"."main"."documents" WHERE kind='layer' AND title='${file.replace(/'/g, "''")}' LIMIT 1`, { enabled: !!file });

  const views = rows(vu.data);
  const defined = views.length;
  const everUsed = views.filter((v) => v.used).length;
  const top = views.slice(0, 6);
  const off = rows(rvu.data).find((r) => String(r.run_label).endsWith("official"));
  const reb = rows(rebuild.data);
  const committed = reb.find((r) => r.layer_label === "committed");
  const rebuilt = reb.find((r) => r.layer_label === "rebuilt");

  return (
    <div>
      <Head kicker="the artifact under study" title="The semantic layer — and how little of it gets used">
        One source per entity, then joins, then views. The bytes are real; the utilization is the finding.
      </Head>

      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(120px,1fr))", gap: 22, margin: "2px 0 18px" }}>
        {vu.isLoading ? <Stat value="…" label="views" /> : <>
          <Stat value={String(defined)} label="views defined" />
          <Stat value={String(everUsed)} label="ever referenced" sub="across all 30 runs" />
          <Stat value={off ? String(N(off.views_used)) : "—"} label="used by the best run" color={ARM.malloy} sub={`of ${defined}`} />
          <Stat value={`${defined - everUsed}`} label="never used by any run" color={PATH.sql} sub={`${Math.round(100 * (defined - everUsed) / (defined || 1))}% dead weight`} />
        </>}
      </div>

      <Figure caption={<>Every defined view, ordered by how many submitted Malloy answers reference it. <b style={{ color: ARM.malloy }}>Filled</b> = used at least once; <b style={{ color: INK.faint }}>faint</b> = never referenced by any run. The agent reaches for SQL or re-authors inline rather than the layer.</>}>
        {vu.isLoading ? <Loading label="computing utilization…" /> : (
          <div style={{ display: "flex", flexWrap: "wrap", gap: 3 }}>
            {views.map((v) => (
              <div key={String(v.view_name)} title={`${v.view_name} — referenced ${N(v.referenced)}×`}
                style={{ width: 13, height: 13, borderRadius: 2, background: v.used ? ARM.malloy : "#e0ddd3",
                  opacity: v.used ? Math.min(1, 0.4 + N(v.referenced) / 40) : 1 }} />
            ))}
          </div>
        )}
      </Figure>

      <div style={{ display: "flex", gap: 30, flexWrap: "wrap", marginBottom: 8 }}>
        <div>
          <div style={{ fontFamily: SANS, fontSize: 11, letterSpacing: "0.05em", textTransform: "uppercase", color: INK.faint, marginBottom: 5 }}>distinct views used, per held-out run</div>
          {rvu.isLoading ? <Loading label="…" /> : (
            <table style={{ borderCollapse: "collapse" }}>
              <tbody>
                {rows(rvu.data).map((r) => (
                  <tr key={String(r.run_label)}>
                    <td style={{ ...tdL, fontSize: 12 }}>{String(r.run_label).replace("Malloy · ", "")}</td>
                    <td style={{ ...td, fontWeight: 700 }}>{N(r.views_used)}<span style={{ color: INK.faint, fontWeight: 400 }}> / {defined}</span></td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
        <div>
          <div style={{ fontFamily: SANS, fontSize: 11, letterSpacing: "0.05em", textTransform: "uppercase", color: INK.faint, marginBottom: 5 }}>the few views that carry the load</div>
          {vu.isLoading ? <Loading label="…" /> : (
            <table style={{ borderCollapse: "collapse" }}>
              <tbody>
                {top.map((v) => (
                  <tr key={String(v.view_name)}><td style={{ ...tdL, fontFamily: MONO, fontSize: 11.5 }}>{String(v.view_name)}</td><td style={td}>{N(v.referenced)}×</td></tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      </div>

      <Rule />

      <Head kicker="read the source" title="The model files">{files.isLoading ? "Loading files…" : `${rows(files.data).length} files. Click to read the Malloy.`}</Head>
      <div style={{ display: "flex", gap: 16, flexWrap: "wrap" }}>
        <div style={{ minWidth: 220 }}>
          {files.isLoading ? <Loading label="…" /> : (
            <table style={{ borderCollapse: "collapse", width: "100%" }}>
              <thead><tr><th style={thL}>file</th><th style={th}>chars</th></tr></thead>
              <tbody>
                {rows(files.data).map((r) => (
                  <tr key={String(r.title)} style={{ cursor: "pointer", background: file === r.title ? "#eaf1f7" : "transparent" }} onClick={() => setFile(String(r.title))}>
                    <td style={{ ...tdL, fontFamily: MONO, fontSize: 11.5, color: ARM.malloy }}>{String(r.title)}</td>
                    <td style={td}>{N(r.chars).toLocaleString()}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
        <div style={{ flex: "1 1 320px" }}>
          {file ? (body.isLoading ? <Loading label={`loading ${file}…`} /> : (
            <pre style={{ margin: 0, padding: 12, fontFamily: MONO, fontSize: 10.5, background: INK.paper, border: `1px solid ${INK.rule}`, borderRadius: 4, overflow: "auto", maxHeight: 420, whiteSpace: "pre-wrap" }}>{String(rows(body.data)[0]?.content ?? "")}</pre>
          )) : <p style={{ fontFamily: SERIF, fontStyle: "italic", fontSize: 13, color: INK.muted }}>Select a file to read its source.</p>}
        </div>
      </div>

      <Rule />

      <Head kicker="did fixing the layer help?" title="The rebuild that didn’t move the score">
        A full rebuild fixed the AVG defect at the source (build-gate findings 18→1) — but it was net-negative and was parked, not shipped.
      </Head>
      {rebuild.isLoading ? <Loading label="…" /> : (
        <div style={{ display: "flex", gap: 26, alignItems: "center", flexWrap: "wrap" }}>
          <div><div style={{ fontFamily: MONO, fontSize: 24, color: INK.text }}>{committed ? pct(committed.avg_acc) : "—"}</div><div style={{ fontSize: 11, color: INK.faint }}>committed layer · train (avg)</div></div>
          <span style={{ color: INK.faint }}>→</span>
          <div><div style={{ fontFamily: MONO, fontSize: 24, color: PATH.sql }}>{rebuilt ? `${N(rebuilt.mn)}/${N(rebuilt.n)}` : "—"}</div><div style={{ fontSize: 11, color: INK.faint }}>rebuilt layer · train</div></div>
          <p style={{ flex: "1 1 260px", fontFamily: SERIF, fontSize: 13, color: INK.muted, lineHeight: 1.5, margin: 0 }}>
            The fix recovered nothing on the score (SQL + the skill already passed those tasks), and the from-scratch regen <b>dropped the counterfactual surfaces</b> the old layer had — a net −2 on train. The substrate’s value isn’t being realized: the agent routes around the layer regardless.
          </p>
        </div>
      )}
    </div>
  );
}


// ───────── TracesTab.tsx ─────────

function TracesTab() {
  const runsQ = useSQLQuery(`SELECT run_id, run_label FROM "agentic_malloy_story"."main"."runs" WHERE arm='malloy' AND split='test' ORDER BY correct DESC`);
  const ex = useSQLQuery(`SELECT
      (SELECT task_id FROM "agentic_malloy_story"."main"."results" WHERE run_label='${OFFICIAL}' AND has_malloy AND is_correct ORDER BY TRY_CAST(task_id AS INT) LIMIT 1) AS clean_win,
      (SELECT task_id FROM "agentic_malloy_story"."main"."results" WHERE run_label='${CONTROLLED}' AND hit_limit ORDER BY TRY_CAST(task_id AS INT) LIMIT 1) AS thrash`);
  const exemplar = rows(ex.data)[0] || {};

  const [runLabel, setRunLabel] = useDiveState<string>("trace_run", OFFICIAL);
  const [task, setTask] = useDiveState<string>("trace_task", "1443");
  const rrun = rows(runsQ.data);
  const runId = rrun.find((r) => r.run_label === runLabel)?.run_id;

  const trace = useSQLQuery(
    `SELECT kind, tool, status, ms, arg, files, output, t
      FROM "agentic_malloy_story"."main"."trace_events"
      WHERE run_id='${esc(runId)}' AND task_id='${esc(task)}'
      ORDER BY ord`,
    { enabled: !!runId && !!task },
  );
  const verdict = useSQLQuery(
    `SELECT is_correct, answer_path, predicted, gold FROM "agentic_malloy_story"."main"."results" WHERE run_label='${esc(runLabel)}' AND task_id='${esc(task)}' LIMIT 1`,
    { enabled: !!task },
  );
  const tr = rows(trace.data);
  const v = rows(verdict.data)[0];

  const presets: [string, string, string][] = [
    ["AVG-view failure", PREFIX, "1443"],
    ["SQL off-ramp", OFFICIAL, "1443"],
    ["clean win", OFFICIAL, String(exemplar.clean_win ?? "1")],
    ["thrash / limit", CONTROLLED, String(exemplar.thrash ?? "1")],
  ];
  const isErr = (s: unknown) => String(s ?? "").toLowerCase().includes("err");

  return (
    <div>
      <Head kicker="what the agent actually did" title="Agent trace explorer">
        The live tool-by-tool trace from the controllog — explore → author → run → submit, with each tool’s result and errors.
      </Head>

      <div style={{ display: "flex", gap: 7, flexWrap: "wrap", marginBottom: 12 }}>
        {presets.map(([label, rl, tk]) => {
          const active = runLabel === rl && task === tk;
          return (
            <button key={label} onClick={() => { setRunLabel(rl); setTask(tk); }}
              style={{ fontFamily: SANS, fontSize: 11.5, padding: "5px 10px", borderRadius: 4, cursor: "pointer",
                border: `1px solid ${active ? ARM.malloy : INK.rule}`, background: active ? "#eaf1f7" : INK.paper,
                color: active ? ARM.malloy : INK.text, fontWeight: active ? 700 : 400 }}>{label}</button>
          );
        })}
      </div>

      <div style={{ display: "flex", gap: 14, flexWrap: "wrap", marginBottom: 12, fontFamily: SANS, fontSize: 12, alignItems: "center" }}>
        <label>run <select value={runLabel} onChange={(e) => setRunLabel(e.target.value)} style={sel}>{rrun.map((r) => <option key={String(r.run_id)} value={String(r.run_label)}>{String(r.run_label)}</option>)}</select></label>
        <label>task <input value={task} onChange={(e) => setTask(e.target.value)} style={{ ...sel, fontFamily: MONO, width: 70 }} /></label>
        {v ? <span style={{ fontSize: 12, color: INK.muted }}>submitted as <b style={{ color: v.answer_path === "sql" ? PATH.sql : ARM.malloy }}>{String(v.answer_path)}</b> · predicted <b style={{ fontFamily: MONO }}>{String(v.predicted)}</b> vs gold <b style={{ fontFamily: MONO }}>{String(v.gold)}</b> <span style={{ color: v.is_correct ? ARM.baseline : PATH.sql, fontWeight: 700 }}>{v.is_correct ? "✓" : "✗"}</span></span> : null}
      </div>

      {trace.isLoading ? <Loading label="loading trace…" /> :
        tr.length === 0 ? <p style={{ fontFamily: SERIF, fontStyle: "italic", color: INK.muted }}>No trace events for this run / task.</p> : (
          <div style={{ display: "flex", flexDirection: "column", gap: 5 }}>
            {tr.map((e, i) => {
              const think = e.kind === "model_completion";
              const call = e.kind === "tool_call";
              const err = e.kind === "tool_result" && isErr(e.status);
              const color = think ? INK.faint : call ? ARM.malloy : err ? PATH.sql : ARM.baseline;
              const label = think ? "think" : call ? `→ ${String(e.tool)}` : `${err ? "✗" : "✓"} ${String(e.tool ?? "result")}`;
              const arg = e.arg ? String(e.arg) : e.files ? `files: ${String(e.files)}` : "";
              const out = e.kind === "tool_result" && e.output ? String(e.output) : "";
              return (
                <div key={i} style={{ display: "flex", gap: 10, alignItems: "flex-start", fontFamily: SANS }}>
                  <span style={{ fontFamily: MONO, fontSize: 10, color: INK.faint, paddingTop: 3, minWidth: 56 }}>{String(e.t)}</span>
                  <span style={{ fontFamily: MONO, fontSize: 12, fontWeight: 600, color, minWidth: 116 }}>
                    {label}{e.ms ? <span style={{ color: INK.faint, fontWeight: 400 }}> {N(e.ms)}ms</span> : null}
                  </span>
                  <div style={{ flex: 1, minWidth: 0 }}>
                    {arg ? <pre style={{ margin: 0, fontFamily: MONO, fontSize: 10.5, color: INK.text, background: INK.paper, border: `1px solid ${INK.rule}`, borderRadius: 4, padding: "4px 8px", overflowX: "auto", whiteSpace: "pre-wrap", maxHeight: 110 }}>{arg.slice(0, 700)}</pre> : null}
                    {out ? <pre style={{ margin: arg ? "3px 0 0" : 0, fontFamily: MONO, fontSize: 10, color: err ? PATH.sql : INK.muted, background: INK.panel, borderRadius: 4, padding: "3px 8px", overflowX: "auto", whiteSpace: "pre-wrap", maxHeight: 80 }}>{out.slice(0, 400)}</pre> : null}
                  </div>
                </div>
              );
            })}
          </div>
        )}
    </div>
  );
}


// ───────── dive.tsx ─────────

export default function StoryDive() {
  const [tab, setTab] = useDiveState<string>("tab", "story");
  return (
    <div style={{ background: INK.bg, color: INK.text, minHeight: "100vh", fontFamily: SANS }}>
      <div style={{ maxWidth: 880, margin: "0 auto", padding: "26px 22px 60px" }}>
        {/* masthead */}
        <div style={{ borderBottom: `2px solid ${INK.text}`, paddingBottom: 10, marginBottom: 4 }}>
          <div style={{ fontFamily: SANS, fontSize: 11, letterSpacing: "0.14em", textTransform: "uppercase", color: INK.muted }}>A DABstep experiment</div>
          <h1 style={{ fontFamily: SERIF, fontSize: 34, fontWeight: 700, color: INK.text, margin: "4px 0 0", letterSpacing: "-0.02em" }}>Malloy vs. Context</h1>
          <p style={{ fontFamily: SERIF, fontStyle: "italic", fontSize: 15, color: INK.muted, margin: "5px 0 0" }}>
            Is a semantic layer a better substrate for an analytics agent than markdown + SQL?
          </p>
        </div>

        {/* tab nav */}
        <div style={{ display: "flex", gap: 2, borderBottom: `1px solid ${INK.rule}`, margin: "14px 0 24px", flexWrap: "wrap" }}>
          {TABS.map((t) => {
            const active = tab === t.key;
            return (
              <button key={t.key} onClick={() => setTab(t.key)}
                style={{ fontFamily: SANS, fontSize: 13, padding: "8px 14px", cursor: "pointer", background: "transparent",
                  border: "none", borderBottom: active ? `2px solid ${ARM.malloy}` : "2px solid transparent",
                  color: active ? ARM.malloy : INK.muted, fontWeight: active ? 700 : 500, marginBottom: -1 }}>
                {t.label}
              </button>
            );
          })}
        </div>

        {tab === "story" && <StoryTab />}
        {tab === "metrics" && <MetricsTab />}
        {tab === "build" && <BuildTab />}
        {tab === "layer" && <LayerTab />}
        {tab === "traces" && <TracesTab />}
      </div>
    </div>
  );
}

