"""
SQL Generator for database metadata.

Generates SQL COMMENT ON statements from metadata profiles and descriptions.
Supports two modes:
1. Description mode: Uses LLM-generated descriptions (verbose)
2. Facts mode: Uses compact factual notation (token-efficient)
"""

from pathlib import Path

from metadata_generator.annotations import SchemaAnnotations
from metadata_generator.models import SchemaProfile, SchemaDescription
from metadata_generator.persistence import FileSystem, RealFileSystem
from metadata_generator.facts import (
    SchemaFacts,
    extract_schema_facts,
    format_column_facts,
    format_table_facts,
)
from metadata_generator.history import QueryHistoryResult
from metadata_generator.progress import ProgressCallback, ProgressReporter


def escape_sql_string(s: str) -> str:
    """Escape single quotes for SQL strings."""
    return s.replace("'", "''")


def quote_identifier(name: str) -> str:
    """Quote identifier if it contains special characters, spaces, or is unsafe."""
    import re
    # Quote if contains any special characters, or starts with a digit
    if re.search(r"[^a-zA-Z0-9_]", name) or re.match(r"^\d", name):
        return f'"{name}"'
    # Quote SQL reserved words (common subset)
    reserved = {
        "select", "from", "where", "table", "column", "index", "order", "group",
        "by", "insert", "update", "delete", "create", "drop", "alter", "join",
        "on", "and", "or", "not", "null", "is", "in", "like", "between", "as",
        "set", "values", "into", "all", "distinct", "having", "limit", "offset",
        "union", "except", "intersect", "case", "when", "then", "else", "end",
        "exists", "primary", "key", "foreign", "references", "default", "check",
        "constraint", "unique", "view", "schema", "database", "grant", "revoke",
        "with", "recursive", "temporary", "temp", "if", "replace", "cascade",
    }
    if name.lower() in reserved:
        return f'"{name}"'
    return name


def generate_sql_comments(
    profile: SchemaProfile,
    descriptions: SchemaDescription | None = None,
    history: QueryHistoryResult | None = None,
    facts_only: bool = False,
    annotations: SchemaAnnotations | None = None,
) -> str:
    """
    Generate SQL COMMENT ON statements from profile.

    Supports two modes:
    - Facts-only mode (facts_only=True): Compact factual notation optimized for
      text-to-SQL. Uses profile stats + optional query history for join/filter info.
    - Description mode (facts_only=False): Verbose LLM-generated descriptions
      with profile statistics appended.

    Args:
        profile: Schema profile with column statistics
        descriptions: Optional LLM-generated descriptions (ignored in facts_only mode)
        history: Optional query history for join/filter patterns (facts_only mode)
        facts_only: If True, use compact fact notation instead of descriptions
        annotations: Optional domain annotations to merge into comments

    Returns:
        SQL statements as a string
    """
    if facts_only:
        return _generate_facts_sql_comments(profile, history, annotations)
    else:
        return _generate_description_sql_comments(profile, descriptions, annotations)


def _generate_facts_sql_comments(
    profile: SchemaProfile,
    history: QueryHistoryResult | None = None,
    annotations: SchemaAnnotations | None = None,
) -> str:
    """
    Generate SQL COMMENT ON statements using compact fact notation.

    Format: [a,b,c];fk(N:1)->table.col;agg:[SUM,AVG];filter:[=,IN]
    """
    lines = [
        f"-- COMMENT ON statements for schema: {profile.db_id}",
        f"-- Database: {profile.database}",
        f"-- Generated by metadata-generator (facts-only mode)",
        "",
    ]

    # Extract all facts at schema level (handles pk, joins_to, cardinality, etc.)
    schema_facts = extract_schema_facts(profile, history)

    for table_facts in schema_facts.tables:
        table_name = table_facts.table_name
        obj_type = "VIEW" if table_facts.is_view else "TABLE"

        # Table comment: row count, pk, and joins
        table_comment = format_table_facts(table_facts)

        # Merge table annotation if present
        table_ann = annotations.get_table_annotation(table_name) if annotations else None
        if table_ann:
            table_comment = f"{table_comment}. {table_ann}"

        lines.append(f"-- Table: {table_name}")
        lines.append(
            f"COMMENT ON {obj_type} {profile.db_id}.{quote_identifier(table_name)} IS "
            f"'{escape_sql_string(table_comment)}';"
        )
        lines.append("")

        # Generate column comments using fact notation
        for col_facts in table_facts.columns:
            col_comment = format_column_facts(col_facts)

            # Merge column annotation if present
            col_ann = (
                annotations.get_column_annotation(table_name, col_facts.column_name)
                if annotations
                else None
            )
            if col_ann:
                if col_comment:
                    col_comment = f"{col_comment}. {col_ann}"
                else:
                    col_comment = col_ann

            # Skip columns with no useful facts and no annotation
            if not col_comment:
                continue

            quoted_col = quote_identifier(col_facts.column_name)
            lines.append(
                f"COMMENT ON COLUMN {profile.db_id}.{quote_identifier(table_name)}.{quoted_col} IS "
                f"'{escape_sql_string(col_comment)}';"
            )

        lines.append("")

    return "\n".join(lines)


def _generate_description_sql_comments(
    profile: SchemaProfile,
    descriptions: SchemaDescription | None = None,
    annotations: SchemaAnnotations | None = None,
) -> str:
    """
    Generate SQL COMMENT ON statements using LLM descriptions (legacy mode).
    """
    lines = [
        f"-- COMMENT ON statements for schema: {profile.db_id}",
        f"-- Database: {profile.database}",
        f"-- Generated by metadata-generator",
        "",
    ]

    # Build lookup for descriptions
    desc_tables = {}
    if descriptions:
        for t in descriptions.tables:
            desc_tables[t.table_name] = t

    for table in profile.tables:
        table_name = table.name
        obj_type = "VIEW" if table.is_view else "TABLE"
        desc_table = desc_tables.get(table_name)

        # Build table comment
        table_comment_parts = []
        if desc_table:
            table_comment_parts.append(desc_table.description)
        table_comment_parts.append(f"({table.row_count:,} rows)")
        table_comment = " ".join(table_comment_parts)

        # Merge table annotation if present
        table_ann = annotations.get_table_annotation(table_name) if annotations else None
        if table_ann:
            table_comment = f"{table_comment}. {table_ann}"

        lines.append(f"-- Table: {table_name}")
        lines.append(
            f"COMMENT ON {obj_type} {profile.db_id}.{quote_identifier(table_name)} IS "
            f"'{escape_sql_string(table_comment)}';"
        )
        lines.append("")

        # Build column descriptions lookup
        desc_columns = {}
        if desc_table:
            for c in desc_table.columns:
                desc_columns[c.column_name] = c

        # Generate column comments
        for col in table.columns:
            desc_col = desc_columns.get(col.name)

            # Build column comment parts
            parts = []

            # Semantic type from description
            if desc_col and desc_col.semantic_type:
                parts.append(f"[{desc_col.semantic_type}]")

            # Description from LLM or fallback
            if desc_col:
                parts.append(desc_col.description)
            else:
                parts.append(f"{col.dtype} column")

            # Stats from profile
            stats = []
            stats.append(col.dtype)

            if col.approx_unique is not None:
                stats.append(f"{col.approx_unique:,} distinct")

            if col.null_percentage > 0:
                stats.append(f"{col.null_percentage:.0f}% null")

            if col.min_value is not None and col.max_value is not None:
                # Truncate long values
                min_str = str(col.min_value)[:30]
                max_str = str(col.max_value)[:30]
                stats.append(f"range: {min_str}..{max_str}")

            # Add shape info for string columns
            if col.detected_pattern:
                stats.append(f"pattern: {col.detected_pattern}")
            if col.avg_length is not None:
                stats.append(f"avg {col.avg_length:.0f} chars")

            if stats:
                parts.append(f"({', '.join(stats)})")

            col_comment = " ".join(parts)

            # Merge column annotation if present
            col_ann = (
                annotations.get_column_annotation(table_name, col.name)
                if annotations
                else None
            )
            if col_ann:
                col_comment = f"{col_comment}. {col_ann}"

            quoted_col = quote_identifier(col.name)
            lines.append(
                f"COMMENT ON COLUMN {profile.db_id}.{quote_identifier(table_name)}.{quoted_col} IS "
                f"'{escape_sql_string(col_comment)}';"
            )

        lines.append("")

    return "\n".join(lines)


def save_sql_comments(
    profile: SchemaProfile,
    descriptions: SchemaDescription | None = None,
    output_dir: str = "output/sql",
    history: QueryHistoryResult | None = None,
    facts_only: bool = False,
    annotations: SchemaAnnotations | None = None,
    fs: FileSystem | None = None,
) -> Path:
    """
    Save COMMENT ON statements to a .sql file.

    Args:
        profile: Schema profile
        descriptions: Optional LLM descriptions (ignored in facts_only mode)
        output_dir: Output directory
        history: Optional query history for join/filter patterns (facts_only mode)
        facts_only: If True, use compact fact notation
        annotations: Optional domain annotations to merge into comments
        fs: FileSystem implementation (defaults to RealFileSystem)

    Returns:
        Path to the saved file
    """
    if fs is None:
        fs = RealFileSystem()
    fs.ensure_dir(Path(output_dir))
    filename = f"{profile.database}_{profile.db_id}_comments.sql"
    output_path = Path(output_dir) / filename

    sql = generate_sql_comments(profile, descriptions, history, facts_only, annotations)
    fs.write_text(output_path, sql)

    return output_path


def execute_sql_comments(
    sql_path: Path | str,
    database: str = "bird_bench",
    verbose: bool = False,
    on_progress: ProgressCallback | None = None,
) -> bool:
    """
    Execute SQL COMMENT statements against MotherDuck.

    Reads the SQL file and executes statements using the Python duckdb module.
    Uses proper SQL splitting that handles dollar-quoted strings.

    Args:
        sql_path: Path to the SQL file to execute
        database: MotherDuck database name
        verbose: Print progress for each table
        on_progress: Optional callback for progress reporting

    Returns:
        True if all statements executed successfully
    """
    from metadata_generator.connection import MotherDuckConnection
    from metadata_generator.history import split_sql_statements

    progress = ProgressReporter(on_progress, enabled=on_progress is not None)

    sql_path = Path(sql_path)
    if not sql_path.exists():
        progress(f"ERROR: SQL file not found: {sql_path}")
        return False

    # Read SQL file
    with open(sql_path) as f:
        sql = f.read()

    # Split into statements (handles dollar-quoted strings properly)
    statements = split_sql_statements(sql)
    progress(f"Executing {len(statements)} statements...")

    success_count = 0
    error_count = 0

    with MotherDuckConnection(database) as db:
        for i, stmt in enumerate(statements, 1):
            try:
                db.conn.execute(stmt)
                success_count += 1
                if verbose and ("COMMENT ON TABLE" in stmt or "COMMENT ON VIEW" in stmt):
                    # Extract table/view name for progress
                    for keyword in ("COMMENT ON TABLE", "COMMENT ON VIEW"):
                        if keyword in stmt:
                            parts = stmt.split(keyword)[1].split(" IS ")[0].strip()
                            progress(f"  {parts}")
                            break
            except Exception as e:
                error_count += 1
                progress(f"ERROR on statement {i}: {e}")
                if verbose:
                    progress(f"  Statement: {stmt[:100]}...")

    result_msg = f"Results: {success_count} successful"
    if error_count > 0:
        result_msg += f", {error_count} failed"
    progress(result_msg)

    return error_count == 0
